//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accion
    {
        public Accion()
        {
            this.StatusAlcanceKardexes = new HashSet<StatusAlcanceKardex>();
        }
    
        public int Pk_IdAccion { get; set; }
        public int Fk_IdCampania__UE { get; set; }
        public int Fk_IdTipoDeRecurso__SIS { get; set; }
        public int Fk_IdTipoDeAccion__SIS { get; set; }
        public int Fk_IdUnidadDeMedida__SIS { get; set; }
        public int FK_IdPersona__SIS { get; set; }
        public string Actividad { get; set; }
        public string Indicador { get; set; }
        public Nullable<int> Meta_Ene { get; set; }
        public Nullable<int> Meta_Feb { get; set; }
        public Nullable<int> Meta_Mar { get; set; }
        public Nullable<int> Meta_Abr { get; set; }
        public Nullable<int> Meta_May { get; set; }
        public Nullable<int> Meta_Jun { get; set; }
        public Nullable<int> Meta_Jul { get; set; }
        public Nullable<int> Meta_Ago { get; set; }
        public Nullable<int> Meta_Sep { get; set; }
        public Nullable<int> Meta_Oct { get; set; }
        public Nullable<int> Meta_Nov { get; set; }
        public Nullable<int> Meta_Dic { get; set; }
        public double Costo { get; set; }
        public string Justificacion { get; set; }
        public Nullable<int> Fk_IdStatusAlcance__SIS { get; set; }
        public Nullable<double> imp_Ene { get; set; }
        public Nullable<double> imp_Feb { get; set; }
        public Nullable<double> imp_Mar { get; set; }
        public Nullable<double> imp_Abr { get; set; }
        public Nullable<double> imp_May { get; set; }
        public Nullable<double> imp_Jun { get; set; }
        public Nullable<double> imp_Jul { get; set; }
        public Nullable<double> imp_Ago { get; set; }
        public Nullable<double> imp_Sep { get; set; }
        public Nullable<double> imp_Oct { get; set; }
        public Nullable<double> imp_Nov { get; set; }
        public Nullable<double> imp_Dic { get; set; }
        public Nullable<int> Fk_IdTipoActividad { get; set; }
    
        public virtual StatusAlcance StatusAlcance { get; set; }
        public virtual TipoDeRecurso TipoDeRecurso { get; set; }
        public virtual UnidadDeMedida UnidadDeMedida { get; set; }
        public virtual ICollection<StatusAlcanceKardex> StatusAlcanceKardexes { get; set; }
        public virtual TipoDeAccion TipoDeAccion { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Campania Campania { get; set; }
    }
}
