//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadXAccion_Repro
    {
        public ActividadXAccion_Repro()
        {
            this.ProgramaAnualAdq_Repro = new HashSet<ProgramaAnualAdq_Repro>();
        }
    
        public int Pk_IdActividadXAccion { get; set; }
        public Nullable<int> Fk_IdActividadXAccion_Orig { get; set; }
        public int Fk_IdAccionXCampania { get; set; }
        public int Fk_IdTipoActividad { get; set; }
        public int Fk_IdUnidadDeMedida { get; set; }
        public int Fk_IdTipoDeRecurso { get; set; }
        public int FK_IdPersona { get; set; }
        public string Actividad { get; set; }
        public string Indicador { get; set; }
        public Nullable<decimal> Meta_Ene { get; set; }
        public Nullable<decimal> Meta_Feb { get; set; }
        public Nullable<decimal> Meta_Mar { get; set; }
        public Nullable<decimal> Meta_Abr { get; set; }
        public Nullable<decimal> Meta_May { get; set; }
        public Nullable<decimal> Meta_Jun { get; set; }
        public Nullable<decimal> Meta_Jul { get; set; }
        public Nullable<decimal> Meta_Ago { get; set; }
        public Nullable<decimal> Meta_Sep { get; set; }
        public Nullable<decimal> Meta_Oct { get; set; }
        public Nullable<decimal> Meta_Nov { get; set; }
        public Nullable<decimal> Meta_Dic { get; set; }
        public string Justificacion { get; set; }
        public Nullable<int> Fk_IdStatusActividad { get; set; }
        public Nullable<double> imp_Ene { get; set; }
        public Nullable<double> imp_Feb { get; set; }
        public Nullable<double> imp_Mar { get; set; }
        public Nullable<double> imp_Abr { get; set; }
        public Nullable<double> imp_May { get; set; }
        public Nullable<double> imp_Jun { get; set; }
        public Nullable<double> imp_Jul { get; set; }
        public Nullable<double> imp_Ago { get; set; }
        public Nullable<double> imp_Sep { get; set; }
        public Nullable<double> imp_Oct { get; set; }
        public Nullable<double> imp_Nov { get; set; }
        public Nullable<double> imp_Dic { get; set; }
        public double imp_Anual { get; set; }
        public Nullable<decimal> Meta_Anual { get; set; }
        public Nullable<decimal> Asignadas { get; set; }
        public string EstadoDeAsignacion { get; set; }
        public string CT_User { get; set; }
        public Nullable<System.DateTime> CT_Date { get; set; }
    
        public virtual AccionXCampania_Repro AccionXCampania_Repro { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual StatusActividad StatusActividad { get; set; }
        public virtual TipoActividad TipoActividad { get; set; }
        public virtual TipoDeRecurso TipoDeRecurso { get; set; }
        public virtual UnidadDeMedida UnidadDeMedida { get; set; }
        public virtual ICollection<ProgramaAnualAdq_Repro> ProgramaAnualAdq_Repro { get; set; }
    }
}
