//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anio
    {
        public Anio()
        {
            this.Inventarios = new HashSet<Inventario>();
            this.GastoOps = new HashSet<GastoOp>();
            this.GastoTransvs = new HashSet<GastoTransv>();
            this.UnidadResponsableXSubComponentes = new HashSet<UnidadResponsableXSubComponente>();
            this.PorcentajeXDireccionGenerals = new HashSet<PorcentajeXDireccionGeneral>();
            this.UnidadResponsableXSubComponentePres = new HashSet<UnidadResponsableXSubComponentePre>();
            this.UnidadDeMedidas = new HashSet<UnidadDeMedida>();
            this.ProyectoPresupuestoes = new HashSet<ProyectoPresupuesto>();
            this.ProgramaAnualAdq_Repro = new HashSet<ProgramaAnualAdq_Repro>();
            this.ProyectoAutorizadoes = new HashSet<ProyectoAutorizado>();
            this.PresXAURs = new HashSet<PresXAUR>();
            this.CapituloPartidas = new HashSet<CapituloPartida>();
            this.ConceptoPartidas = new HashSet<ConceptoPartida>();
            this.Partidas = new HashSet<Partida>();
            this.TipoDeBiens = new HashSet<TipoDeBien>();
            this.BienOServs = new HashSet<BienOServ>();
            this.Componentes = new HashSet<Componente>();
            this.PEFXEstadoes = new HashSet<PEFXEstado>();
            this.ProgramaAnualAdqs = new HashSet<ProgramaAnualAdq>();
            this.MinistracionesXComites = new HashSet<MinistracionesXComite>();
        }
    
        public int Pk_IdAnio { get; set; }
        public int Anio1 { get; set; }
    
        public virtual ICollection<Inventario> Inventarios { get; set; }
        public virtual ICollection<GastoOp> GastoOps { get; set; }
        public virtual ICollection<GastoTransv> GastoTransvs { get; set; }
        public virtual ICollection<UnidadResponsableXSubComponente> UnidadResponsableXSubComponentes { get; set; }
        public virtual ICollection<PorcentajeXDireccionGeneral> PorcentajeXDireccionGenerals { get; set; }
        public virtual ICollection<UnidadResponsableXSubComponentePre> UnidadResponsableXSubComponentePres { get; set; }
        public virtual ICollection<UnidadDeMedida> UnidadDeMedidas { get; set; }
        public virtual ICollection<ProyectoPresupuesto> ProyectoPresupuestoes { get; set; }
        public virtual ICollection<ProgramaAnualAdq_Repro> ProgramaAnualAdq_Repro { get; set; }
        public virtual ICollection<ProyectoAutorizado> ProyectoAutorizadoes { get; set; }
        public virtual ICollection<PresXAUR> PresXAURs { get; set; }
        public virtual ICollection<CapituloPartida> CapituloPartidas { get; set; }
        public virtual ICollection<ConceptoPartida> ConceptoPartidas { get; set; }
        public virtual ICollection<Partida> Partidas { get; set; }
        public virtual ICollection<TipoDeBien> TipoDeBiens { get; set; }
        public virtual ICollection<BienOServ> BienOServs { get; set; }
        public virtual ICollection<Componente> Componentes { get; set; }
        public virtual ICollection<PEFXEstado> PEFXEstadoes { get; set; }
        public virtual ICollection<ProgramaAnualAdq> ProgramaAnualAdqs { get; set; }
        public virtual ICollection<MinistracionesXComite> MinistracionesXComites { get; set; }
    }
}
