//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtendidoMov_Repro
    {
        public int Pk_IdAtendidoMov { get; set; }
        public Nullable<int> Fk_IdAtendidoMov_Orig { get; set; }
        public int Fk_IdCampania { get; set; }
        public string NombrePVI_SitioInspeccion { get; set; }
        public string MateriaInspeccion { get; set; }
        public int NumInspeccion_Ant { get; set; }
        public int NumMedidasAplicadas_Ant { get; set; }
        public int NumInspeccion_Act { get; set; }
        public int NumMedidasAplicadas_Act { get; set; }
    
        public virtual Campania_Repro Campania_Repro { get; set; }
    }
}
