//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtendidoIno_Repro
    {
        public int Pk_IdAtendidoIno { get; set; }
        public Nullable<int> Fk_IdAtendidoIno_Orig { get; set; }
        public int Fk_IdCampania { get; set; }
        public int FK_IdTipoUnidad_Atendido { get; set; }
        public int NumUnidades { get; set; }
        public int NumProductores { get; set; }
        public int NumUnidadesProductivas { get; set; }
        public string Especie_Cultivo { get; set; }
    
        public virtual Campania_Repro Campania_Repro { get; set; }
        public virtual TipoUnidad_Atendido TipoUnidad_Atendido { get; set; }
    }
}
