//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtendidoSV
    {
        public int Pk_IdAtendidoSV { get; set; }
        public int Fk_IdCampania { get; set; }
        public int Fk_IdMunicipio { get; set; }
        public int NumUnidadesProduccion { get; set; }
        public string Cultivo { get; set; }
        public double Superficie { get; set; }
        public int NumUnidProdAtendida_Ant { get; set; }
        public decimal SuperficieAtendida_Ant { get; set; }
        public double Prevalencia_Ant { get; set; }
        public int NumUnidProdAtendida_Act { get; set; }
        public decimal SuperficieAtendida_Act { get; set; }
        public double Prevalencia_Act { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
    
        public virtual Municipio Municipio { get; set; }
        public virtual Campania Campania { get; set; }
    }
}
