//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banco
    {
        public Banco()
        {
            this.UnidadEjecutoras = new HashSet<UnidadEjecutora>();
            this.UnidadEjecutoras1 = new HashSet<UnidadEjecutora>();
            this.UnidadEjecutoras2 = new HashSet<UnidadEjecutora>();
        }
    
        public int Pk_IdBanco { get; set; }
        public string Clave { get; set; }
        public string NombreCorto { get; set; }
        public string RazonSocial { get; set; }
    
        public virtual ICollection<UnidadEjecutora> UnidadEjecutoras { get; set; }
        public virtual ICollection<UnidadEjecutora> UnidadEjecutoras1 { get; set; }
        public virtual ICollection<UnidadEjecutora> UnidadEjecutoras2 { get; set; }
    }
}
