//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiario
    {
        public int Pk_IdBeneficiario { get; set; }
        public int Fk_IdActividad__UE { get; set; }
        public int Fk_IdProductor__UE { get; set; }
    
        public virtual Productor Productor { get; set; }
        public virtual Actividad Actividad { get; set; }
    }
}
