//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienOservByUnidadMedida
    {
        public int Pk_IdBienOServByUnidadMedida { get; set; }
        public int Fk_IdBienOServ { get; set; }
        public int Fk_IdUnidadDeMedida { get; set; }
        public System.DateTime CT_Date { get; set; }
        public string CT_User { get; set; }
    
        public virtual BienOServ BienOServ { get; set; }
        public virtual UnidadDeMedida UnidadDeMedida { get; set; }
    }
}
