//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienOServ
    {
        public BienOServ()
        {
            this.ProgramaAnualAdq_Repro = new HashSet<ProgramaAnualAdq_Repro>();
            this.Inventarios = new HashSet<Inventario>();
            this.NecesidadXAccions = new HashSet<NecesidadXAccion>();
            this.ProgramaAnualAdqs = new HashSet<ProgramaAnualAdq>();
            this.BienOservByUnidadMedidas = new HashSet<BienOservByUnidadMedida>();
        }
    
        public int Pk_IdBienOServ { get; set; }
        public int Fk_IdTipoDeBien { get; set; }
        public string CABMS { get; set; }
        public string Nombre { get; set; }
        public string Especificacion { get; set; }
        public int Fk_IdAnio { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
        public Nullable<bool> esTransversal { get; set; }
        public Nullable<decimal> porcentajeMaximo { get; set; }
        public Nullable<decimal> precioMaximo { get; set; }
        public Nullable<int> OrdenReporteIntegral { get; set; }
        public Nullable<int> Fk_id_bienOservn { get; set; }
    
        public virtual ICollection<ProgramaAnualAdq_Repro> ProgramaAnualAdq_Repro { get; set; }
        public virtual Anio Anio { get; set; }
        public virtual TipoDeBien TipoDeBien { get; set; }
        public virtual ICollection<Inventario> Inventarios { get; set; }
        public virtual ICollection<NecesidadXAccion> NecesidadXAccions { get; set; }
        public virtual ICollection<ProgramaAnualAdq> ProgramaAnualAdqs { get; set; }
        public virtual ICollection<BienOservByUnidadMedida> BienOservByUnidadMedidas { get; set; }
        public virtual BienServN BienServN { get; set; }
    }
}
