//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campania
    {
        public Campania()
        {
            this.Accions = new HashSet<Accion>();
            this.AccionXCampanias = new HashSet<AccionXCampania>();
            this.AtendidoInoes = new HashSet<AtendidoIno>();
            this.AtendidoMovs = new HashSet<AtendidoMov>();
            this.AtendidoSAs = new HashSet<AtendidoSA>();
            this.AtendidoSACs = new HashSet<AtendidoSAC>();
            this.AtendidoSVs = new HashSet<AtendidoSV>();
            this.CierreMensuals = new HashSet<CierreMensual>();
            this.ImportanciaCultivoSACs = new HashSet<ImportanciaCultivoSAC>();
            this.ImportanciaCultivoSVs = new HashSet<ImportanciaCultivoSV>();
            this.ImportanciaEconomicaSAs = new HashSet<ImportanciaEconomicaSA>();
            this.ImportanciaEnfermedadSAs = new HashSet<ImportanciaEnfermedadSA>();
            this.ImportanciaEnfermedadSACs = new HashSet<ImportanciaEnfermedadSAC>();
            this.ImportanciaInoes = new HashSet<ImportanciaIno>();
            this.ImportanciaPIVMovs = new HashSet<ImportanciaPIVMov>();
            this.ImportanciaPlagaSVs = new HashSet<ImportanciaPlagaSV>();
            this.ImportanciaProgramaMovs = new HashSet<ImportanciaProgramaMov>();
            this.InoCompSAs = new HashSet<InoCompSA>();
            this.InoCompSACs = new HashSet<InoCompSAC>();
            this.InoCompSVs = new HashSet<InoCompSV>();
            this.InoImportanciaSAs = new HashSet<InoImportanciaSA>();
            this.InoImportanciaSACs = new HashSet<InoImportanciaSAC>();
            this.InoImportanciaSVs = new HashSet<InoImportanciaSV>();
            this.InoUnidadesCertSAs = new HashSet<InoUnidadesCertSA>();
            this.InoUnidadesCertSACs = new HashSet<InoUnidadesCertSAC>();
            this.InoUnidadesCertSVs = new HashSet<InoUnidadesCertSV>();
            this.Mov_Atendido = new HashSet<Mov_Atendido>();
            this.Mov_ImportanciaPIV = new HashSet<Mov_ImportanciaPIV>();
            this.Mov_ImportanciaProg = new HashSet<Mov_ImportanciaProg>();
            this.ProgramaAnualAdqs = new HashSet<ProgramaAnualAdq>();
            this.SA_Atendido = new HashSet<SA_Atendido>();
            this.SA_ImportanciaEnfermedad = new HashSet<SA_ImportanciaEnfermedad>();
            this.SAC_Atendido = new HashSet<SAC_Atendido>();
            this.SACImportanciaCultivoes = new HashSet<SACImportanciaCultivo>();
            this.SACImportanciaEnfermedads = new HashSet<SACImportanciaEnfermedad>();
            this.SA_Poblacion = new HashSet<SA_Poblacion>();
            this.StatusCampaniaKardexes = new HashSet<StatusCampaniaKardex>();
            this.SVAtendidoes = new HashSet<SVAtendido>();
            this.SVImportanciaCultivoes = new HashSet<SVImportanciaCultivo>();
            this.SVImportanciaPlagas = new HashSet<SVImportanciaPlaga>();
            this.UnidadesCertificarInoSAs = new HashSet<UnidadesCertificarInoSA>();
            this.UnidadesCertificarInoSACs = new HashSet<UnidadesCertificarInoSAC>();
            this.UnidadesCertificarInoSVs = new HashSet<UnidadesCertificarInoSV>();
            this.MinistracionDetalles = new HashSet<MinistracionDetalle>();
        }
    
        public int Pk_IdCampania { get; set; }
        public string NombreCampania { get; set; }
        public string Introduccion { get; set; }
        public string SituacionActual { get; set; }
        public string ObjetivoEstrategico { get; set; }
        public string MetaAnual { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string NombreArchivoAnexo { get; set; }
        public string NombreArchivoInforme { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
        public Nullable<int> Fk_IdCoordinador { get; set; }
        public Nullable<int> Fk_IdProyectoPresupuesto { get; set; }
        public Nullable<decimal> RecFed { get; set; }
        public Nullable<decimal> RecEst { get; set; }
        public Nullable<decimal> RecPro { get; set; }
        public Nullable<decimal> RecTot { get; set; }
        public string StatusKardex { get; set; }
        public Nullable<bool> esEditable { get; set; }
        public Nullable<System.DateTime> FechaModificacionStatus { get; set; }
        public Nullable<decimal> RecSol_Fed { get; set; }
        public Nullable<decimal> RecSol_Est { get; set; }
        public Nullable<decimal> RecSol_Pro { get; set; }
        public string NombreInf_PrimerTrim { get; set; }
        public string NombreInf_SegundoTrim { get; set; }
        public string NombreInf_TercerTrim { get; set; }
        public string NombreInf_CuartoTrim { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual ProyectoPresupuesto ProyectoPresupuesto { get; set; }
        public virtual ICollection<Accion> Accions { get; set; }
        public virtual ICollection<AccionXCampania> AccionXCampanias { get; set; }
        public virtual ICollection<AtendidoIno> AtendidoInoes { get; set; }
        public virtual ICollection<AtendidoMov> AtendidoMovs { get; set; }
        public virtual ICollection<AtendidoSA> AtendidoSAs { get; set; }
        public virtual ICollection<AtendidoSAC> AtendidoSACs { get; set; }
        public virtual ICollection<AtendidoSV> AtendidoSVs { get; set; }
        public virtual ICollection<CierreMensual> CierreMensuals { get; set; }
        public virtual ICollection<ImportanciaCultivoSAC> ImportanciaCultivoSACs { get; set; }
        public virtual ICollection<ImportanciaCultivoSV> ImportanciaCultivoSVs { get; set; }
        public virtual ICollection<ImportanciaEconomicaSA> ImportanciaEconomicaSAs { get; set; }
        public virtual ICollection<ImportanciaEnfermedadSA> ImportanciaEnfermedadSAs { get; set; }
        public virtual ICollection<ImportanciaEnfermedadSAC> ImportanciaEnfermedadSACs { get; set; }
        public virtual ICollection<ImportanciaIno> ImportanciaInoes { get; set; }
        public virtual ICollection<ImportanciaPIVMov> ImportanciaPIVMovs { get; set; }
        public virtual ICollection<ImportanciaPlagaSV> ImportanciaPlagaSVs { get; set; }
        public virtual ICollection<ImportanciaProgramaMov> ImportanciaProgramaMovs { get; set; }
        public virtual ICollection<InoCompSA> InoCompSAs { get; set; }
        public virtual ICollection<InoCompSAC> InoCompSACs { get; set; }
        public virtual ICollection<InoCompSV> InoCompSVs { get; set; }
        public virtual ICollection<InoImportanciaSA> InoImportanciaSAs { get; set; }
        public virtual ICollection<InoImportanciaSAC> InoImportanciaSACs { get; set; }
        public virtual ICollection<InoImportanciaSV> InoImportanciaSVs { get; set; }
        public virtual ICollection<InoUnidadesCertSA> InoUnidadesCertSAs { get; set; }
        public virtual ICollection<InoUnidadesCertSAC> InoUnidadesCertSACs { get; set; }
        public virtual ICollection<InoUnidadesCertSV> InoUnidadesCertSVs { get; set; }
        public virtual ICollection<Mov_Atendido> Mov_Atendido { get; set; }
        public virtual ICollection<Mov_ImportanciaPIV> Mov_ImportanciaPIV { get; set; }
        public virtual ICollection<Mov_ImportanciaProg> Mov_ImportanciaProg { get; set; }
        public virtual ICollection<ProgramaAnualAdq> ProgramaAnualAdqs { get; set; }
        public virtual ICollection<SA_Atendido> SA_Atendido { get; set; }
        public virtual ICollection<SA_ImportanciaEnfermedad> SA_ImportanciaEnfermedad { get; set; }
        public virtual ICollection<SAC_Atendido> SAC_Atendido { get; set; }
        public virtual ICollection<SACImportanciaCultivo> SACImportanciaCultivoes { get; set; }
        public virtual ICollection<SACImportanciaEnfermedad> SACImportanciaEnfermedads { get; set; }
        public virtual ICollection<SA_Poblacion> SA_Poblacion { get; set; }
        public virtual ICollection<StatusCampaniaKardex> StatusCampaniaKardexes { get; set; }
        public virtual ICollection<SVAtendido> SVAtendidoes { get; set; }
        public virtual ICollection<SVImportanciaCultivo> SVImportanciaCultivoes { get; set; }
        public virtual ICollection<SVImportanciaPlaga> SVImportanciaPlagas { get; set; }
        public virtual ICollection<UnidadesCertificarInoSA> UnidadesCertificarInoSAs { get; set; }
        public virtual ICollection<UnidadesCertificarInoSAC> UnidadesCertificarInoSACs { get; set; }
        public virtual ICollection<UnidadesCertificarInoSV> UnidadesCertificarInoSVs { get; set; }
        public virtual ICollection<MinistracionDetalle> MinistracionDetalles { get; set; }
    }
}
