//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campania_Repro
    {
        public Campania_Repro()
        {
            this.AccionXCampania_Repro = new HashSet<AccionXCampania_Repro>();
            this.AtendidoIno_Repro = new HashSet<AtendidoIno_Repro>();
            this.AtendidoMov_Repro = new HashSet<AtendidoMov_Repro>();
            this.AtendidoSA_Repro = new HashSet<AtendidoSA_Repro>();
            this.AtendidoSAC_Repro = new HashSet<AtendidoSAC_Repro>();
            this.AtendidoSV_Repro = new HashSet<AtendidoSV_Repro>();
            this.ImportanciaCultivoSAC_Repro = new HashSet<ImportanciaCultivoSAC_Repro>();
            this.ImportanciaCultivoSV_Repro = new HashSet<ImportanciaCultivoSV_Repro>();
            this.ImportanciaEconomicaSA_Repro = new HashSet<ImportanciaEconomicaSA_Repro>();
            this.ImportanciaEnfermedadSA_Repro = new HashSet<ImportanciaEnfermedadSA_Repro>();
            this.ImportanciaEnfermedadSAC_Repro = new HashSet<ImportanciaEnfermedadSAC_Repro>();
            this.ImportanciaIno_Repro = new HashSet<ImportanciaIno_Repro>();
            this.ImportanciaPIVMov_Repro = new HashSet<ImportanciaPIVMov_Repro>();
            this.ImportanciaPlagaSV_Repro = new HashSet<ImportanciaPlagaSV_Repro>();
            this.ImportanciaProgramaMov_Repro = new HashSet<ImportanciaProgramaMov_Repro>();
            this.StatusCampaniaKardex_Repro = new HashSet<StatusCampaniaKardex_Repro>();
            this.UnidadesCertificarInoSA_Repro = new HashSet<UnidadesCertificarInoSA_Repro>();
            this.UnidadesCertificarInoSAC_Repro = new HashSet<UnidadesCertificarInoSAC_Repro>();
            this.UnidadesCertificarInoSV_Repro = new HashSet<UnidadesCertificarInoSV_Repro>();
            this.ProgramaAnualAdq_Repro = new HashSet<ProgramaAnualAdq_Repro>();
        }
    
        public int Pk_IdCampania { get; set; }
        public Nullable<int> Fk_IdCampania_Orig { get; set; }
        public string NombreCampania { get; set; }
        public string Introduccion { get; set; }
        public string SituacionActual { get; set; }
        public string ObjetivoEstrategico { get; set; }
        public string MetaAnual { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string NombreArchivoAnexo { get; set; }
        public string NombreArchivoInforme { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
        public Nullable<int> Fk_IdCoordinador { get; set; }
        public Nullable<int> Fk_IdProyectoPresupuesto { get; set; }
        public Nullable<decimal> RecFed { get; set; }
        public Nullable<decimal> RecEst { get; set; }
        public Nullable<decimal> RecPro { get; set; }
        public Nullable<decimal> RecTot { get; set; }
        public string StatusKardex { get; set; }
        public Nullable<bool> esEditable { get; set; }
        public Nullable<System.DateTime> FechaModificacionStatus { get; set; }
        public Nullable<decimal> RecSol_Fed { get; set; }
        public Nullable<decimal> RecSol_Est { get; set; }
        public Nullable<decimal> RecSol_Pro { get; set; }
    
        public virtual ICollection<AccionXCampania_Repro> AccionXCampania_Repro { get; set; }
        public virtual ICollection<AtendidoIno_Repro> AtendidoIno_Repro { get; set; }
        public virtual ICollection<AtendidoMov_Repro> AtendidoMov_Repro { get; set; }
        public virtual ICollection<AtendidoSA_Repro> AtendidoSA_Repro { get; set; }
        public virtual ICollection<AtendidoSAC_Repro> AtendidoSAC_Repro { get; set; }
        public virtual ICollection<AtendidoSV_Repro> AtendidoSV_Repro { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual ICollection<ImportanciaCultivoSAC_Repro> ImportanciaCultivoSAC_Repro { get; set; }
        public virtual ICollection<ImportanciaCultivoSV_Repro> ImportanciaCultivoSV_Repro { get; set; }
        public virtual ICollection<ImportanciaEconomicaSA_Repro> ImportanciaEconomicaSA_Repro { get; set; }
        public virtual ICollection<ImportanciaEnfermedadSA_Repro> ImportanciaEnfermedadSA_Repro { get; set; }
        public virtual ICollection<ImportanciaEnfermedadSAC_Repro> ImportanciaEnfermedadSAC_Repro { get; set; }
        public virtual ICollection<ImportanciaIno_Repro> ImportanciaIno_Repro { get; set; }
        public virtual ICollection<ImportanciaPIVMov_Repro> ImportanciaPIVMov_Repro { get; set; }
        public virtual ICollection<ImportanciaPlagaSV_Repro> ImportanciaPlagaSV_Repro { get; set; }
        public virtual ICollection<ImportanciaProgramaMov_Repro> ImportanciaProgramaMov_Repro { get; set; }
        public virtual ProyectoPresupuesto ProyectoPresupuesto { get; set; }
        public virtual ICollection<StatusCampaniaKardex_Repro> StatusCampaniaKardex_Repro { get; set; }
        public virtual ICollection<UnidadesCertificarInoSA_Repro> UnidadesCertificarInoSA_Repro { get; set; }
        public virtual ICollection<UnidadesCertificarInoSAC_Repro> UnidadesCertificarInoSAC_Repro { get; set; }
        public virtual ICollection<UnidadesCertificarInoSV_Repro> UnidadesCertificarInoSV_Repro { get; set; }
        public virtual ICollection<ProgramaAnualAdq_Repro> ProgramaAnualAdq_Repro { get; set; }
    }
}
