//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo
    {
        public Cargo()
        {
            this.CertificadoCargoes = new HashSet<CertificadoCargo>();
            this.Representantes1 = new HashSet<Representante1>();
            this.Personas = new HashSet<Persona>();
        }
    
        public int Pk_IdCargo { get; set; }
        public string Nombre { get; set; }
        public int Fk_IdTipoDeUnidad { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
    
        public virtual ICollection<CertificadoCargo> CertificadoCargoes { get; set; }
        public virtual ICollection<Representante1> Representantes1 { get; set; }
        public virtual ICollection<Persona> Personas { get; set; }
    }
}
