//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificadoPersona
    {
        public int Pk_IdCertificadoPersona { get; set; }
        public int Fk_IdPersona { get; set; }
        public int Fk_IdCertificado { get; set; }
        public string Documento { get; set; }
        public Nullable<System.DateTime> VigenciaDocumento { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual Certificacion Certificacion { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
