//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CierreMensualSolicitudApertura
    {
        public int Pk_IdCierreMensualSolicitudApertura { get; set; }
        public int Fk_IdCierreMensual { get; set; }
        public string MotivosApertura { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool estaAtendido { get; set; }
        public string RespuestaApertura { get; set; }
        public Nullable<bool> aperturaAceptada { get; set; }
        public Nullable<System.DateTime> FechaCierreAutomatico { get; set; }
    
        public virtual CierreMensual CierreMensual { get; set; }
    }
}
