//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Componente
    {
        public Componente()
        {
            this.Incentivoes = new HashSet<Incentivo>();
        }
    
        public int Pk_IdComponente { get; set; }
        public int Fk_IdPrograma__SIS { get; set; }
        public string Nombre { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
        public Nullable<int> Fk_IdAnio { get; set; }
    
        public virtual Anio Anio { get; set; }
        public virtual Programa Programa { get; set; }
        public virtual ICollection<Incentivo> Incentivoes { get; set; }
    }
}
