//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptoPartida
    {
        public ConceptoPartida()
        {
            this.Partidas = new HashSet<Partida>();
        }
    
        public int Pk_IdConceptoPartida { get; set; }
        public int Fk_IdCapituloPartida__SIS { get; set; }
        public string Nombre { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
        public int Fk_IdAnio { get; set; }
    
        public virtual ICollection<Partida> Partidas { get; set; }
        public virtual CapituloPartida CapituloPartida1 { get; set; }
        public virtual Anio Anio { get; set; }
    }
}
