//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuadroCompXPantalla
    {
        public int Pk_IdCuadroCompXPantalla { get; set; }
        public Nullable<int> Fk_IdUnidadResponsable__UE { get; set; }
        public string NombrePantalla { get; set; }
        public bool CT_LIVE { get; set; }
    
        public virtual UnidadResponsable UnidadResponsable { get; set; }
    }
}
