//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentUser
    {
        public string IdSession { get; set; }
        public string IdUser { get; set; }
        public string Rol { get; set; }
        public System.DateTime DateLogin { get; set; }
        public Nullable<System.DateTime> DateLogout { get; set; }
        public string UserName { get; set; }
        public string Nombre { get; set; }
        public string Estado { get; set; }
        public string InstanciaEjecutora { get; set; }
    }
}
