//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosFirma
    {
        public int Pk_IdFirmas { get; set; }
        public string Puesto { get; set; }
        public string NombreFirmante { get; set; }
        public int Orden { get; set; }
        public int Fk_IdFirmasAutorizadas { get; set; }
    
        public virtual FirmasAutorizada FirmasAutorizada { get; set; }
    }
}
