//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestinoProduccion
    {
        public DestinoProduccion()
        {
            this.ImportanciaCultivoSVs = new HashSet<ImportanciaCultivoSV>();
            this.ImportanciaEconomicaSAs = new HashSet<ImportanciaEconomicaSA>();
            this.ImportanciaInoes = new HashSet<ImportanciaIno>();
            this.ImportanciaCultivoSV_Repro = new HashSet<ImportanciaCultivoSV_Repro>();
            this.ImportanciaEconomicaSA_Repro = new HashSet<ImportanciaEconomicaSA_Repro>();
            this.ImportanciaIno_Repro = new HashSet<ImportanciaIno_Repro>();
        }
    
        public int Pk_IdDestinoProduccion { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<ImportanciaCultivoSV> ImportanciaCultivoSVs { get; set; }
        public virtual ICollection<ImportanciaEconomicaSA> ImportanciaEconomicaSAs { get; set; }
        public virtual ICollection<ImportanciaIno> ImportanciaInoes { get; set; }
        public virtual ICollection<ImportanciaCultivoSV_Repro> ImportanciaCultivoSV_Repro { get; set; }
        public virtual ICollection<ImportanciaEconomicaSA_Repro> ImportanciaEconomicaSA_Repro { get; set; }
        public virtual ICollection<ImportanciaIno_Repro> ImportanciaIno_Repro { get; set; }
    }
}
