//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado
    {
        public Estado()
        {
            this.Mov_Atendido = new HashSet<Mov_Atendido>();
            this.Mov_ImportanciaPIV = new HashSet<Mov_ImportanciaPIV>();
            this.Municipios = new HashSet<Municipio>();
            this.Productors = new HashSet<Productor>();
            this.Proveedors = new HashSet<Proveedor>();
            this.PresupuestoXEstadoes = new HashSet<PresupuestoXEstado>();
            this.FirmasAutorizadas = new HashSet<FirmasAutorizada>();
            this.ProyectoPresupuestoes = new HashSet<ProyectoPresupuesto>();
            this.UnidadEjecutoras = new HashSet<UnidadEjecutora>();
            this.PresXAURs = new HashSet<PresXAUR>();
            this.PEFXEstadoes = new HashSet<PEFXEstado>();
            this.Licitacions = new HashSet<Licitacion>();
            this.ActaComisions = new HashSet<ActaComision>();
        }
    
        public int Pk_IdEstado { get; set; }
        public string Nombre { get; set; }
        public int CT_CreatedBy { get; set; }
        public System.DateTime CT_CreatedDate { get; set; }
        public Nullable<int> CT_ModifiedBy { get; set; }
        public Nullable<System.DateTime> CT_ModifiedDate { get; set; }
        public bool CT_LIVE { get; set; }
        public int Fk_IdRegion { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual ICollection<Mov_Atendido> Mov_Atendido { get; set; }
        public virtual ICollection<Mov_ImportanciaPIV> Mov_ImportanciaPIV { get; set; }
        public virtual ICollection<Municipio> Municipios { get; set; }
        public virtual ICollection<Productor> Productors { get; set; }
        public virtual ICollection<Proveedor> Proveedors { get; set; }
        public virtual ICollection<PresupuestoXEstado> PresupuestoXEstadoes { get; set; }
        public virtual ICollection<FirmasAutorizada> FirmasAutorizadas { get; set; }
        public virtual ICollection<ProyectoPresupuesto> ProyectoPresupuestoes { get; set; }
        public virtual ICollection<UnidadEjecutora> UnidadEjecutoras { get; set; }
        public virtual ICollection<PresXAUR> PresXAURs { get; set; }
        public virtual ICollection<PEFXEstado> PEFXEstadoes { get; set; }
        public virtual ICollection<Licitacion> Licitacions { get; set; }
        public virtual ICollection<ActaComision> ActaComisions { get; set; }
    }
}
