//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILE
    {
        public FILE()
        {
            this.Aperturas = new HashSet<Apertura>();
            this.Falloes = new HashSet<Fallo>();
            this.JuntaAclaracions = new HashSet<JuntaAclaracion>();
            this.Licitacions = new HashSet<Licitacion>();
        }
    
        public int Pk_IdFiles { get; set; }
        public string FileName { get; set; }
    
        public virtual ICollection<Apertura> Aperturas { get; set; }
        public virtual ICollection<Fallo> Falloes { get; set; }
        public virtual ICollection<JuntaAclaracion> JuntaAclaracions { get; set; }
        public virtual ICollection<Licitacion> Licitacions { get; set; }
    }
}
