//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmasAutorizada
    {
        public FirmasAutorizada()
        {
            this.DatosFirmas = new HashSet<DatosFirma>();
        }
    
        public int Pk_IdFirmasAutorizadas { get; set; }
        public int Fk_IdEstado { get; set; }
        public int Fk_IdReportes { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Reporte Reporte { get; set; }
        public virtual ICollection<DatosFirma> DatosFirmas { get; set; }
    }
}
