//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncionZootecnica
    {
        public FuncionZootecnica()
        {
            this.ImportanciaEconomicaSAs = new HashSet<ImportanciaEconomicaSA>();
            this.ImportanciaCultivoSACs = new HashSet<ImportanciaCultivoSAC>();
            this.UnidadesCertificarInoSAs = new HashSet<UnidadesCertificarInoSA>();
            this.ImportanciaCultivoSAC_Repro = new HashSet<ImportanciaCultivoSAC_Repro>();
            this.ImportanciaEconomicaSA_Repro = new HashSet<ImportanciaEconomicaSA_Repro>();
            this.UnidadesCertificarInoSA_Repro = new HashSet<UnidadesCertificarInoSA_Repro>();
        }
    
        public int Pk_IdFuncionZootecnica { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<ImportanciaEconomicaSA> ImportanciaEconomicaSAs { get; set; }
        public virtual ICollection<ImportanciaCultivoSAC> ImportanciaCultivoSACs { get; set; }
        public virtual ICollection<UnidadesCertificarInoSA> UnidadesCertificarInoSAs { get; set; }
        public virtual ICollection<ImportanciaCultivoSAC_Repro> ImportanciaCultivoSAC_Repro { get; set; }
        public virtual ICollection<ImportanciaEconomicaSA_Repro> ImportanciaEconomicaSA_Repro { get; set; }
        public virtual ICollection<UnidadesCertificarInoSA_Repro> UnidadesCertificarInoSA_Repro { get; set; }
    }
}
