//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastoOp
    {
        public int Pk_IdGastoOp { get; set; }
        public int FK_IdAnio { get; set; }
        public string Concepto { get; set; }
        public double PorcentajePEFXEstado { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
    
        public virtual Anio Anio { get; set; }
    }
}
