//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    
    public partial class GetPEFXEstados_Result1
    {
        public string Estado { get; set; }
        public Nullable<decimal> SistemaInform { get; set; }
        public Nullable<decimal> Capacitacion { get; set; }
        public Nullable<decimal> Divulgacion { get; set; }
        public Nullable<decimal> Emergencias { get; set; }
        public Nullable<decimal> Gtotransv { get; set; }
        public Nullable<decimal> Comp_CampFitoZoo { get; set; }
        public Nullable<decimal> Comp_InspVig { get; set; }
        public Nullable<decimal> Comp_VigCuarentenaria { get; set; }
        public Nullable<decimal> Comp_IAAP { get; set; }
        public Nullable<decimal> Componentes { get; set; }
        public Nullable<decimal> GtoInversion { get; set; }
        public Nullable<decimal> GtoOperacion { get; set; }
        public Nullable<decimal> Importe { get; set; }
    }
}
