//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    
    public partial class GetPresComite_ByComite_Result1
    {
        public int IdComite { get; set; }
        public string Comite { get; set; }
        public decimal RecursoAsignado { get; set; }
    }
}
