//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GirosXProv
    {
        public int PK_IdGiroXProv { get; set; }
        public int Fk_IdProveedor { get; set; }
        public int Fk_IdTipoDeBien { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
        public virtual TipoDeBien TipoDeBien { get; set; }
    }
}
