//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportanciaEnfermedadSA
    {
        public int Pk_IdImportanciaEnfermedadSA { get; set; }
        public int Fk_IdCampania { get; set; }
        public int Fk_IdMunicipio { get; set; }
        public int Fk_IdEspecie { get; set; }
        public int FK_IdUnidadMedidaProduccion { get; set; }
        public int NumUnidadesProduccion { get; set; }
        public Nullable<int> NumCabezas { get; set; }
        public double PrevEnfermedad { get; set; }
        public double CantEstimadasPerdidas { get; set; }
        public double ValorEstimadoPerdida { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
        public string Enfermedad { get; set; }
    
        public virtual Municipio Municipio { get; set; }
        public virtual Especie Especie { get; set; }
        public virtual UnidadMedidaProduccion UnidadMedidaProduccion { get; set; }
        public virtual Campania Campania { get; set; }
    }
}
