//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportanciaProgramaMov_Repro
    {
        public int Pk_IdImportanciaProgramaMov { get; set; }
        public Nullable<int> Fk_IdImportanciaProgramaMov_Orig { get; set; }
        public int Fk_IdCampania { get; set; }
        public int NumTotInspeccion { get; set; }
        public int NumRetenciones { get; set; }
        public int NumRetornos { get; set; }
        public int NumDestrucciones { get; set; }
        public int NumGuardaCustodia { get; set; }
        public int NumTratamiento_Acon { get; set; }
        public int NumCuarentenas { get; set; }
    
        public virtual Campania_Repro Campania_Repro { get; set; }
    }
}
