//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportanciaIno_Repro
    {
        public int Pk_IdImportanciaIno { get; set; }
        public Nullable<int> Fk_IdImportanciaIno_Orig { get; set; }
        public int Fk_IdCampania { get; set; }
        public int FK_IdTipoProduccion { get; set; }
        public int FK_IdDestinoProduccion { get; set; }
        public int FK_IdTendenciaProduccion { get; set; }
        public int NumUnidadesEspecie { get; set; }
        public Nullable<bool> esAfectado { get; set; }
        public int NumUnidadesAfectadas { get; set; }
        public string Especie_Cultivo { get; set; }
    
        public virtual Campania_Repro Campania_Repro { get; set; }
        public virtual DestinoProduccion DestinoProduccion { get; set; }
        public virtual TendenciaProduccion TendenciaProduccion { get; set; }
        public virtual TipoProduccion TipoProduccion { get; set; }
    }
}
