//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportanciaEconomicaSA_Repro
    {
        public int Pk_IdImportanciaEconomicaSA { get; set; }
        public Nullable<int> Fk_IdImportanciaEconomicaSA_Orig { get; set; }
        public int Fk_IdCampania { get; set; }
        public int Fk_IdMunicipio { get; set; }
        public int Fk_IdEspecie { get; set; }
        public int FK_IdFuncionZootecnica { get; set; }
        public int FK_IdUnidadMedidaProduccion { get; set; }
        public int FK_IdDestinoProduccion { get; set; }
        public int NumUnidadesProduccion { get; set; }
        public int NumCabezas { get; set; }
        public int CantidadProduccion { get; set; }
        public int ValorProduccion { get; set; }
        public Nullable<int> NumAnimalesEnPieExportados { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
    
        public virtual Campania_Repro Campania_Repro { get; set; }
        public virtual DestinoProduccion DestinoProduccion { get; set; }
        public virtual Especie Especie { get; set; }
        public virtual FuncionZootecnica FuncionZootecnica { get; set; }
        public virtual Municipio Municipio { get; set; }
        public virtual UnidadMedidaProduccion UnidadMedidaProduccion { get; set; }
    }
}
