//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportanciaPlagaSV_Repro
    {
        public int Pk_IdImportanciaPlagaSV { get; set; }
        public Nullable<int> Fk_IdImportanciaPlagaSV_Orig { get; set; }
        public int Fk_IdCampania { get; set; }
        public int Fk_IdMunicipio { get; set; }
        public string Cultivo { get; set; }
        public double SuperficieAfectada { get; set; }
        public int NumUnidadesProdAfectada { get; set; }
        public double PrevalenciaInfestacion { get; set; }
        public double VolumenPerdida { get; set; }
        public double ValorPerdida { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
    
        public virtual Campania_Repro Campania_Repro { get; set; }
        public virtual Municipio Municipio { get; set; }
    }
}
