//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InoCompSV
    {
        public int Pk_IdInoCompSV { get; set; }
        public int FK_IdCampania { get; set; }
        public int Fk_IdMunicipio { get; set; }
        public string Cultivo { get; set; }
        public string Empresa { get; set; }
        public Nullable<int> UnidadesProduccion { get; set; }
        public Nullable<int> Toneladas { get; set; }
        public Nullable<int> Produccion { get; set; }
        public Nullable<int> Extraccion { get; set; }
        public Nullable<int> Acopio { get; set; }
        public Nullable<int> ProcesoPrimario { get; set; }
        public Nullable<int> UpAnioAnterior { get; set; }
        public Nullable<int> UpAnioActual { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
    
        public virtual Municipio Municipio { get; set; }
        public virtual Campania Campania { get; set; }
    }
}
