//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instalacion
    {
        public int Pk_IdInstalacion { get; set; }
        public int Fk_IdUnidadEjecutora { get; set; }
        public int Fk_IdTipoDeInstalacion { get; set; }
        public string Nombre { get; set; }
        public string Ubicacion { get; set; }
        public string Utilizacion { get; set; }
        public string region { get; set; }
        public string Estatus { get; set; }
        public string Certificado { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
        public Nullable<int> Fk_IdTipoAdquisicion_SIS { get; set; }
    
        public virtual TipoInstalacion TipoInstalacion { get; set; }
        public virtual UnidadEjecutora UnidadEjecutora { get; set; }
        public virtual TipoAdquisicion TipoAdquisicion { get; set; }
    }
}
