//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licitacion_Capitulo
    {
        public int Pk_IdLicitacion_Capitulo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Fk_IdLicitacion__INFO { get; set; }
        public Nullable<int> Fk_IdCapituloPartida_INFO { get; set; }
    
        public virtual CapituloPartidaLicitacion CapituloPartidaLicitacion { get; set; }
        public virtual Licitacion Licitacion { get; set; }
    }
}
