//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licitacion
    {
        public Licitacion()
        {
            this.Aperturas = new HashSet<Apertura>();
            this.Falloes = new HashSet<Fallo>();
            this.JuntaAclaracions = new HashSet<JuntaAclaracion>();
            this.Licitacion_Capitulo = new HashSet<Licitacion_Capitulo>();
        }
    
        public int Pk_IdLicitacion { get; set; }
        public string Folio { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaJuntaAclaracion { get; set; }
        public Nullable<System.DateTime> FechaApertura { get; set; }
        public Nullable<System.DateTime> FechaFallo { get; set; }
        public Nullable<int> Fk_IdFiles__INFO { get; set; }
        public Nullable<int> Fk_IdEstado__SIS { get; set; }
        public Nullable<int> Fk_IdUnidadEjecutora__UE { get; set; }
        public string Documento { get; set; }
    
        public virtual ICollection<Apertura> Aperturas { get; set; }
        public virtual ICollection<Fallo> Falloes { get; set; }
        public virtual FILE FILE { get; set; }
        public virtual ICollection<JuntaAclaracion> JuntaAclaracions { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual UnidadEjecutora UnidadEjecutora { get; set; }
        public virtual ICollection<Licitacion_Capitulo> Licitacion_Capitulo { get; set; }
    }
}
