//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MesByTrimestre
    {
        public MesByTrimestre()
        {
            this.ActaComisions = new HashSet<ActaComision>();
        }
    
        public int Pk_IdMesTrimestre { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<ActaComision> ActaComisions { get; set; }
    }
}
