//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MinistracionDetalle
    {
        public int Pk_IdMinistracionDetalle { get; set; }
        public int Fk_IdMinistracionesXComite { get; set; }
        public int Fk_IdCampania { get; set; }
        public decimal Importe { get; set; }
        public Nullable<System.DateTime> CT_Date { get; set; }
        public string CT_User { get; set; }
    
        public virtual Campania Campania { get; set; }
        public virtual MinistracionesXComite MinistracionesXComite { get; set; }
    }
}
