//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MinistracionesXComite
    {
        public MinistracionesXComite()
        {
            this.MinistracionDetalles = new HashSet<MinistracionDetalle>();
            this.MinistracionesXComite1 = new HashSet<MinistracionesXComite>();
        }
    
        public int Pk_IdMinistracionesXComite { get; set; }
        public int Fk_IdInstanciaEjecutora { get; set; }
        public int Fk_IdTipoDeRecurso { get; set; }
        public decimal Importe { get; set; }
        public System.DateTime Fecha { get; set; }
        public string NumCtaCheques { get; set; }
        public string CLABE { get; set; }
        public Nullable<int> Fk_IdBanco { get; set; }
        public Nullable<decimal> ImporteDetalles { get; set; }
        public int Fk_IdAnio { get; set; }
        public string Documento { get; set; }
        public Nullable<System.DateTime> CT_Date { get; set; }
        public string CT_User { get; set; }
    
        public virtual Anio Anio { get; set; }
        public virtual TipoDeRecurso TipoDeRecurso { get; set; }
        public virtual ICollection<MinistracionDetalle> MinistracionDetalles { get; set; }
        public virtual ICollection<MinistracionesXComite> MinistracionesXComite1 { get; set; }
        public virtual MinistracionesXComite MinistracionesXComite2 { get; set; }
        public virtual UnidadEjecutora UnidadEjecutora { get; set; }
    }
}
