//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_SENASICAEntities : DbContext
    {
        public DB_SENASICAEntities()
            : base("name=DB_SENASICAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Predio> Predios { get; set; }
        public virtual DbSet<SubPredio> SubPredios { get; set; }
        public virtual DbSet<Anio> Anios { get; set; }
        public virtual DbSet<ConceptoPartida> ConceptoPartidas { get; set; }
        public virtual DbSet<Municipio> Municipios { get; set; }
        public virtual DbSet<Partida> Partidas { get; set; }
        public virtual DbSet<Programa> Programas { get; set; }
        public virtual DbSet<SubComponente> SubComponentes { get; set; }
        public virtual DbSet<TipoDeRecurso> TipoDeRecursoes { get; set; }
        public virtual DbSet<TipoDeUnidad> TipoDeUnidads { get; set; }
        public virtual DbSet<UnidadDeMedida> UnidadDeMedidas { get; set; }
        public virtual DbSet<Beneficiario> Beneficiarios { get; set; }
        public virtual DbSet<CapituloPartida> CapituloPartidas { get; set; }
        public virtual DbSet<Vigencia> Vigencias { get; set; }
        public virtual DbSet<TipoInstalacion> TipoInstalacions { get; set; }
        public virtual DbSet<Inventario> Inventarios { get; set; }
        public virtual DbSet<EstadoBien> EstadoBiens { get; set; }
        public virtual DbSet<Instalacion> Instalacions { get; set; }
        public virtual DbSet<StatusActividad> StatusActividads { get; set; }
        public virtual DbSet<StatusAlcance> StatusAlcances { get; set; }
        public virtual DbSet<StatusUE> StatusUEs { get; set; }
        public virtual DbSet<StatusActividadKardex> StatusActividadKardexes { get; set; }
        public virtual DbSet<StatusAlcanceKardex> StatusAlcanceKardexes { get; set; }
        public virtual DbSet<StatusCampaniaKardex> StatusCampaniaKardexes { get; set; }
        public virtual DbSet<Cargo> Cargoes { get; set; }
        public virtual DbSet<Certificacion> Certificacions { get; set; }
        public virtual DbSet<CertificadoCargo> CertificadoCargoes { get; set; }
        public virtual DbSet<CertificadoPersona> CertificadoPersonas { get; set; }
        public virtual DbSet<FlujoActividad> FlujoActividads { get; set; }
        public virtual DbSet<FlujoAlcance> FlujoAlcances { get; set; }
        public virtual DbSet<Mov_Atendido> Mov_Atendido { get; set; }
        public virtual DbSet<Mov_ImportanciaPIV> Mov_ImportanciaPIV { get; set; }
        public virtual DbSet<SA_Atendido> SA_Atendido { get; set; }
        public virtual DbSet<SA_ImportanciaEnfermedad> SA_ImportanciaEnfermedad { get; set; }
        public virtual DbSet<SA_Poblacion> SA_Poblacion { get; set; }
        public virtual DbSet<SACImportanciaEnfermedad> SACImportanciaEnfermedads { get; set; }
        public virtual DbSet<SVAtendido> SVAtendidoes { get; set; }
        public virtual DbSet<SVImportanciaCultivo> SVImportanciaCultivoes { get; set; }
        public virtual DbSet<SVImportanciaPlaga> SVImportanciaPlagas { get; set; }
        public virtual DbSet<Representante1> Representantes1 { get; set; }
        public virtual DbSet<RepGasto> RepGastoes { get; set; }
        public virtual DbSet<InoCompSA> InoCompSAs { get; set; }
        public virtual DbSet<InoCompSAC> InoCompSACs { get; set; }
        public virtual DbSet<InoCompSV> InoCompSVs { get; set; }
        public virtual DbSet<InoImportanciaSA> InoImportanciaSAs { get; set; }
        public virtual DbSet<InoImportanciaSAC> InoImportanciaSACs { get; set; }
        public virtual DbSet<InoImportanciaSV> InoImportanciaSVs { get; set; }
        public virtual DbSet<InoUnidadesCertSA> InoUnidadesCertSAs { get; set; }
        public virtual DbSet<InoUnidadesCertSAC> InoUnidadesCertSACs { get; set; }
        public virtual DbSet<InoUnidadesCertSV> InoUnidadesCertSVs { get; set; }
        public virtual DbSet<StatusAccion> StatusAccions { get; set; }
        public virtual DbSet<AccionXCampania> AccionXCampanias { get; set; }
        public virtual DbSet<TipoActividad> TipoActividads { get; set; }
        public virtual DbSet<Proveedor> Proveedors { get; set; }
        public virtual DbSet<SACImportanciaCultivo> SACImportanciaCultivoes { get; set; }
        public virtual DbSet<Profesion> Profesions { get; set; }
        public virtual DbSet<Puesto> Puestoes { get; set; }
        public virtual DbSet<Me> Mes { get; set; }
        public virtual DbSet<Presupuesto> Presupuestoes { get; set; }
        public virtual DbSet<Accion> Accions { get; set; }
        public virtual DbSet<GirosXProv> GirosXProvs { get; set; }
        public virtual DbSet<EstadosGeo> EstadosGeos { get; set; }
        public virtual DbSet<geometry_columns> geometry_columns { get; set; }
        public virtual DbSet<MunicipiosGeo> MunicipiosGeos { get; set; }
        public virtual DbSet<spatial_ref_sys> spatial_ref_sys { get; set; }
        public virtual DbSet<SAC_Atendido> SAC_Atendido { get; set; }
        public virtual DbSet<NecesidadXAccion> NecesidadXAccions { get; set; }
        public virtual DbSet<TipoDeBien> TipoDeBiens { get; set; }
        public virtual DbSet<Productor> Productors { get; set; }
        public virtual DbSet<Mov_ImportanciaProg> Mov_ImportanciaProg { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Estado> Estadoes { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<TipoDeAccion> TipoDeAccions { get; set; }
        public virtual DbSet<GastoOp> GastoOps { get; set; }
        public virtual DbSet<GastoTransv> GastoTransvs { get; set; }
        public virtual DbSet<UnidadResponsableXSubComponente> UnidadResponsableXSubComponentes { get; set; }
        public virtual DbSet<VW_PresupuestoXDFG> VW_PresupuestoXDFG { get; set; }
        public virtual DbSet<PorcentajeXDireccionGeneral> PorcentajeXDireccionGenerals { get; set; }
        public virtual DbSet<UnidadResponsable> UnidadResponsables { get; set; }
        public virtual DbSet<PresupuestoXEstado> PresupuestoXEstadoes { get; set; }
        public virtual DbSet<UnidadResponsableXSubComponentePre> UnidadResponsableXSubComponentePres { get; set; }
        public virtual DbSet<FirmasAutorizada> FirmasAutorizadas { get; set; }
        public virtual DbSet<Reporte> Reportes { get; set; }
        public virtual DbSet<DatosFirma> DatosFirmas { get; set; }
        public virtual DbSet<Pantalla> Pantallas { get; set; }
        public virtual DbSet<PrivilegiosXRol> PrivilegiosXRols { get; set; }
        public virtual DbSet<AtendidoSA> AtendidoSAs { get; set; }
        public virtual DbSet<DestinoProduccion> DestinoProduccions { get; set; }
        public virtual DbSet<Especie> Especies { get; set; }
        public virtual DbSet<FuncionZootecnica> FuncionZootecnicas { get; set; }
        public virtual DbSet<ImportanciaCultivoSV> ImportanciaCultivoSVs { get; set; }
        public virtual DbSet<ImportanciaEconomicaSA> ImportanciaEconomicaSAs { get; set; }
        public virtual DbSet<ImportanciaPlagaSV> ImportanciaPlagaSVs { get; set; }
        public virtual DbSet<UnidadMedidaProduccion> UnidadMedidaProduccions { get; set; }
        public virtual DbSet<AtendidoMov> AtendidoMovs { get; set; }
        public virtual DbSet<ImportanciaPIVMov> ImportanciaPIVMovs { get; set; }
        public virtual DbSet<ImportanciaProgramaMov> ImportanciaProgramaMovs { get; set; }
        public virtual DbSet<AtendidoSAC> AtendidoSACs { get; set; }
        public virtual DbSet<ImportanciaCultivoSAC> ImportanciaCultivoSACs { get; set; }
        public virtual DbSet<ImportanciaEnfermedadSAC> ImportanciaEnfermedadSACs { get; set; }
        public virtual DbSet<SistemaProduccion> SistemaProduccions { get; set; }
        public virtual DbSet<TendenciaProduccion> TendenciaProduccions { get; set; }
        public virtual DbSet<TipoProduccion> TipoProduccions { get; set; }
        public virtual DbSet<TipoUnidad_Atendido> TipoUnidad_Atendido { get; set; }
        public virtual DbSet<TipoUnidad_UCAC> TipoUnidad_UCAC { get; set; }
        public virtual DbSet<TipoUnidad_UCSV> TipoUnidad_UCSV { get; set; }
        public virtual DbSet<UnidadesCertificarInoSA> UnidadesCertificarInoSAs { get; set; }
        public virtual DbSet<UnidadesCertificarInoSAC> UnidadesCertificarInoSACs { get; set; }
        public virtual DbSet<UnidadesCertificarInoSV> UnidadesCertificarInoSVs { get; set; }
        public virtual DbSet<AtendidoIno> AtendidoInoes { get; set; }
        public virtual DbSet<ImportanciaEnfermedadSA> ImportanciaEnfermedadSAs { get; set; }
        public virtual DbSet<ImportanciaIno> ImportanciaInoes { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<AtendidoSV> AtendidoSVs { get; set; }
        public virtual DbSet<Banco> Bancoes { get; set; }
        public virtual DbSet<ProyectoPresupuesto> ProyectoPresupuestoes { get; set; }
        public virtual DbSet<UnidadEjecutora> UnidadEjecutoras { get; set; }
        public virtual DbSet<TipoCampania> TipoCampanias { get; set; }
        public virtual DbSet<AccionXCampania_Repro> AccionXCampania_Repro { get; set; }
        public virtual DbSet<AtendidoIno_Repro> AtendidoIno_Repro { get; set; }
        public virtual DbSet<AtendidoMov_Repro> AtendidoMov_Repro { get; set; }
        public virtual DbSet<AtendidoSA_Repro> AtendidoSA_Repro { get; set; }
        public virtual DbSet<AtendidoSAC_Repro> AtendidoSAC_Repro { get; set; }
        public virtual DbSet<AtendidoSV_Repro> AtendidoSV_Repro { get; set; }
        public virtual DbSet<Campania_Repro> Campania_Repro { get; set; }
        public virtual DbSet<ImportanciaCultivoSAC_Repro> ImportanciaCultivoSAC_Repro { get; set; }
        public virtual DbSet<ImportanciaCultivoSV_Repro> ImportanciaCultivoSV_Repro { get; set; }
        public virtual DbSet<ImportanciaEconomicaSA_Repro> ImportanciaEconomicaSA_Repro { get; set; }
        public virtual DbSet<ImportanciaEnfermedadSA_Repro> ImportanciaEnfermedadSA_Repro { get; set; }
        public virtual DbSet<ImportanciaEnfermedadSAC_Repro> ImportanciaEnfermedadSAC_Repro { get; set; }
        public virtual DbSet<ImportanciaIno_Repro> ImportanciaIno_Repro { get; set; }
        public virtual DbSet<ImportanciaPIVMov_Repro> ImportanciaPIVMov_Repro { get; set; }
        public virtual DbSet<ImportanciaPlagaSV_Repro> ImportanciaPlagaSV_Repro { get; set; }
        public virtual DbSet<ImportanciaProgramaMov_Repro> ImportanciaProgramaMov_Repro { get; set; }
        public virtual DbSet<StatusCampaniaKardex_Repro> StatusCampaniaKardex_Repro { get; set; }
        public virtual DbSet<UnidadesCertificarInoSA_Repro> UnidadesCertificarInoSA_Repro { get; set; }
        public virtual DbSet<UnidadesCertificarInoSAC_Repro> UnidadesCertificarInoSAC_Repro { get; set; }
        public virtual DbSet<UnidadesCertificarInoSV_Repro> UnidadesCertificarInoSV_Repro { get; set; }
        public virtual DbSet<CuadroCompXPantalla> CuadroCompXPantallas { get; set; }
        public virtual DbSet<CierreMensualSolicitudApertura> CierreMensualSolicitudAperturas { get; set; }
        public virtual DbSet<RepActividad> RepActividads { get; set; }
        public virtual DbSet<CurrentUser> CurrentUsers { get; set; }
        public virtual DbSet<CierreMensual> CierreMensuals { get; set; }
        public virtual DbSet<TipoAdquisicion> TipoAdquisicions { get; set; }
        public virtual DbSet<RepAdquisicion> RepAdquisicions { get; set; }
        public virtual DbSet<VW_PresupuestoCampania> VW_PresupuestoCampania { get; set; }
        public virtual DbSet<ProgramaAnualAdq_Repro> ProgramaAnualAdq_Repro { get; set; }
        public virtual DbSet<ActividadXAccion_Repro> ActividadXAccion_Repro { get; set; }
        public virtual DbSet<VW_HistoricoReproPT> VW_HistoricoReproPT { get; set; }
        public virtual DbSet<Incentivo> Incentivoes { get; set; }
        public virtual DbSet<ProyectoAutorizado> ProyectoAutorizadoes { get; set; }
        public virtual DbSet<PresXAUR> PresXAURs { get; set; }
        public virtual DbSet<BienOServ> BienOServs { get; set; }
        public virtual DbSet<ProgramasGastosTransversale> ProgramasGastosTransversales { get; set; }
        public virtual DbSet<Componente> Componentes { get; set; }
        public virtual DbSet<PEFXEstado> PEFXEstadoes { get; set; }
        public virtual DbSet<ProgramaAnualAdq> ProgramaAnualAdqs { get; set; }
        public virtual DbSet<Campania> Campanias { get; set; }
        public virtual DbSet<VW_CampaniasMontosTransversales> VW_CampaniasMontosTransversales { get; set; }
        public virtual DbSet<TipoReembolso> TipoReembolsoes { get; set; }
        public virtual DbSet<TesofeDetalle> TesofeDetalles { get; set; }
        public virtual DbSet<TESOFE> TESOFEs { get; set; }
        public virtual DbSet<MinistracionDetalle> MinistracionDetalles { get; set; }
        public virtual DbSet<MinistracionesXComite> MinistracionesXComites { get; set; }
        public virtual DbSet<ActaComision> ActaComisions { get; set; }
        public virtual DbSet<MesByTrimestre> MesByTrimestres { get; set; }
        public virtual DbSet<VW_Users> VW_Users { get; set; }
        public virtual DbSet<Apertura> Aperturas { get; set; }
        public virtual DbSet<Fallo> Falloes { get; set; }
        public virtual DbSet<FILE> FILES { get; set; }
        public virtual DbSet<JuntaAclaracion> JuntaAclaracions { get; set; }
        public virtual DbSet<Licitacion> Licitacions { get; set; }
        public virtual DbSet<CapituloPartidaLicitacion> CapituloPartidaLicitacions { get; set; }
        public virtual DbSet<Licitacion_Capitulo> Licitacion_Capitulo { get; set; }
        public virtual DbSet<Actividad> Actividads { get; set; }
        public virtual DbSet<ActividadXAccion> ActividadXAccions { get; set; }
        public virtual DbSet<FlujoCampania> FlujoCampanias { get; set; }
        public virtual DbSet<StatusCampania> StatusCampanias { get; set; }
        public virtual DbSet<BienOservByUnidadMedida> BienOservByUnidadMedidas { get; set; }
        public virtual DbSet<VW_ReporteAdquisiciones> VW_ReporteAdquisiciones { get; set; }
        public virtual DbSet<BienServN> BienServNs { get; set; }
    
        [DbFunction("DB_SENASICAEntities", "ResumenPresupuestoXDG")]
        public virtual IQueryable<ResumenPresupuestoXDG_Result> ResumenPresupuestoXDG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ResumenPresupuestoXDG_Result>("[DB_SENASICAEntities].[ResumenPresupuestoXDG]()");
        }
    
        public virtual int SP_DELETE_ProyectoAutorizado(Nullable<int> pK_IdProyectoAutorizado, string cT_User, ObjectParameter error)
        {
            var pK_IdProyectoAutorizadoParameter = pK_IdProyectoAutorizado.HasValue ?
                new ObjectParameter("PK_IdProyectoAutorizado", pK_IdProyectoAutorizado) :
                new ObjectParameter("PK_IdProyectoAutorizado", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_ProyectoAutorizado", pK_IdProyectoAutorizadoParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_BienOServ(Nullable<int> pK_IdBienOServ, string cT_User, ObjectParameter error)
        {
            var pK_IdBienOServParameter = pK_IdBienOServ.HasValue ?
                new ObjectParameter("PK_IdBienOServ", pK_IdBienOServ) :
                new ObjectParameter("PK_IdBienOServ", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_BienOServ", pK_IdBienOServParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_Programa(Nullable<int> pK_IdPrograma, string cT_User, ObjectParameter error)
        {
            var pK_IdProgramaParameter = pK_IdPrograma.HasValue ?
                new ObjectParameter("PK_IdPrograma", pK_IdPrograma) :
                new ObjectParameter("PK_IdPrograma", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_Programa", pK_IdProgramaParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_Componente(Nullable<int> pK_IdComponente, string cT_User, ObjectParameter error)
        {
            var pK_IdComponenteParameter = pK_IdComponente.HasValue ?
                new ObjectParameter("PK_IdComponente", pK_IdComponente) :
                new ObjectParameter("PK_IdComponente", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_Componente", pK_IdComponenteParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_Incentivo(Nullable<int> pK_IdIncentivo, string cT_User, ObjectParameter error)
        {
            var pK_IdIncentivoParameter = pK_IdIncentivo.HasValue ?
                new ObjectParameter("PK_IdIncentivo", pK_IdIncentivo) :
                new ObjectParameter("PK_IdIncentivo", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_Incentivo", pK_IdIncentivoParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_SubComponente(Nullable<int> pK_IdSubComponente, string cT_User, ObjectParameter error)
        {
            var pK_IdSubComponenteParameter = pK_IdSubComponente.HasValue ?
                new ObjectParameter("PK_IdSubComponente", pK_IdSubComponente) :
                new ObjectParameter("PK_IdSubComponente", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_SubComponente", pK_IdSubComponenteParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_Presupuesto(Nullable<int> pK_IdPresupuesto, string cT_User, ObjectParameter error)
        {
            var pK_IdPresupuestoParameter = pK_IdPresupuesto.HasValue ?
                new ObjectParameter("PK_IdPresupuesto", pK_IdPresupuesto) :
                new ObjectParameter("PK_IdPresupuesto", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_Presupuesto", pK_IdPresupuestoParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_ProyectoPresupuesto(Nullable<int> pK_IdProyectoPresupuesto, string cT_User, ObjectParameter error)
        {
            var pK_IdProyectoPresupuestoParameter = pK_IdProyectoPresupuesto.HasValue ?
                new ObjectParameter("PK_IdProyectoPresupuesto", pK_IdProyectoPresupuesto) :
                new ObjectParameter("PK_IdProyectoPresupuesto", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_ProyectoPresupuesto", pK_IdProyectoPresupuestoParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_EstadoBien(Nullable<int> pK_IdEstadoBien, string cT_User, ObjectParameter error)
        {
            var pK_IdEstadoBienParameter = pK_IdEstadoBien.HasValue ?
                new ObjectParameter("PK_IdEstadoBien", pK_IdEstadoBien) :
                new ObjectParameter("PK_IdEstadoBien", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_EstadoBien", pK_IdEstadoBienParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_Proveedor(Nullable<int> pK_IdProveedor, string cT_User, ObjectParameter error)
        {
            var pK_IdProveedorParameter = pK_IdProveedor.HasValue ?
                new ObjectParameter("PK_IdProveedor", pK_IdProveedor) :
                new ObjectParameter("PK_IdProveedor", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_Proveedor", pK_IdProveedorParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_TipoActividad(Nullable<int> pK_IdTipoActividad, string cT_User, ObjectParameter error)
        {
            var pK_IdTipoActividadParameter = pK_IdTipoActividad.HasValue ?
                new ObjectParameter("PK_IdTipoActividad", pK_IdTipoActividad) :
                new ObjectParameter("PK_IdTipoActividad", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_TipoActividad", pK_IdTipoActividadParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_TipoDeAccion(Nullable<int> pK_IdTipoDeAccion, string cT_User, ObjectParameter error)
        {
            var pK_IdTipoDeAccionParameter = pK_IdTipoDeAccion.HasValue ?
                new ObjectParameter("PK_IdTipoDeAccion", pK_IdTipoDeAccion) :
                new ObjectParameter("PK_IdTipoDeAccion", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_TipoDeAccion", pK_IdTipoDeAccionParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_TipoDeRecurso(Nullable<int> pK_IdTipoDeRecurso, string cT_User, ObjectParameter error)
        {
            var pK_IdTipoDeRecursoParameter = pK_IdTipoDeRecurso.HasValue ?
                new ObjectParameter("PK_IdTipoDeRecurso", pK_IdTipoDeRecurso) :
                new ObjectParameter("PK_IdTipoDeRecurso", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_TipoDeRecurso", pK_IdTipoDeRecursoParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_TipoDeUnidad(Nullable<int> pK_IdTipoDeUnidad, string cT_User, ObjectParameter error)
        {
            var pK_IdTipoDeUnidadParameter = pK_IdTipoDeUnidad.HasValue ?
                new ObjectParameter("PK_IdTipoDeUnidad", pK_IdTipoDeUnidad) :
                new ObjectParameter("PK_IdTipoDeUnidad", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_TipoDeUnidad", pK_IdTipoDeUnidadParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_TipoInstalacion(Nullable<int> pK_IdTipoInstalacion, string cT_User, ObjectParameter error)
        {
            var pK_IdTipoInstalacionParameter = pK_IdTipoInstalacion.HasValue ?
                new ObjectParameter("PK_IdTipoInstalacion", pK_IdTipoInstalacion) :
                new ObjectParameter("PK_IdTipoInstalacion", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_TipoInstalacion", pK_IdTipoInstalacionParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_UnidadDeMedida(Nullable<int> pK_IdUnidadDeMedida, string cT_User, ObjectParameter error)
        {
            var pK_IdUnidadDeMedidaParameter = pK_IdUnidadDeMedida.HasValue ?
                new ObjectParameter("PK_IdUnidadDeMedida", pK_IdUnidadDeMedida) :
                new ObjectParameter("PK_IdUnidadDeMedida", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_UnidadDeMedida", pK_IdUnidadDeMedidaParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_Productor(Nullable<int> pK_IdProductor, string cT_User, ObjectParameter error)
        {
            var pK_IdProductorParameter = pK_IdProductor.HasValue ?
                new ObjectParameter("PK_IdProductor", pK_IdProductor) :
                new ObjectParameter("PK_IdProductor", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_Productor", pK_IdProductorParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_ProgramaAnualAdq(Nullable<int> pK_IdProgramaAnualAdq, string cT_User, ObjectParameter error)
        {
            var pK_IdProgramaAnualAdqParameter = pK_IdProgramaAnualAdq.HasValue ?
                new ObjectParameter("PK_IdProgramaAnualAdq", pK_IdProgramaAnualAdq) :
                new ObjectParameter("PK_IdProgramaAnualAdq", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_ProgramaAnualAdq", pK_IdProgramaAnualAdqParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_UnidadEjecutora(Nullable<int> pK_IdUnidadEjecutora, string cT_User, ObjectParameter error)
        {
            var pK_IdUnidadEjecutoraParameter = pK_IdUnidadEjecutora.HasValue ?
                new ObjectParameter("PK_IdUnidadEjecutora", pK_IdUnidadEjecutora) :
                new ObjectParameter("PK_IdUnidadEjecutora", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_UnidadEjecutora", pK_IdUnidadEjecutoraParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_UnidadResponsable(Nullable<int> pK_IdUnidadResponsable, string cT_User, ObjectParameter error)
        {
            var pK_IdUnidadResponsableParameter = pK_IdUnidadResponsable.HasValue ?
                new ObjectParameter("PK_IdUnidadResponsable", pK_IdUnidadResponsable) :
                new ObjectParameter("PK_IdUnidadResponsable", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_UnidadResponsable", pK_IdUnidadResponsableParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_Cargo(Nullable<int> pK_IdCargo, string cT_User, ObjectParameter error)
        {
            var pK_IdCargoParameter = pK_IdCargo.HasValue ?
                new ObjectParameter("PK_IdCargo", pK_IdCargo) :
                new ObjectParameter("PK_IdCargo", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_Cargo", pK_IdCargoParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_Certificacion(Nullable<int> pK_IdCertificacion, string cT_User, ObjectParameter error)
        {
            var pK_IdCertificacionParameter = pK_IdCertificacion.HasValue ?
                new ObjectParameter("PK_IdCertificacion", pK_IdCertificacion) :
                new ObjectParameter("PK_IdCertificacion", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_Certificacion", pK_IdCertificacionParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_CertificadoCargo(Nullable<int> pK_IdCertificadoCargo, string cT_User, ObjectParameter error)
        {
            var pK_IdCertificadoCargoParameter = pK_IdCertificadoCargo.HasValue ?
                new ObjectParameter("PK_IdCertificadoCargo", pK_IdCertificadoCargo) :
                new ObjectParameter("PK_IdCertificadoCargo", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_CertificadoCargo", pK_IdCertificadoCargoParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_ConceptoPartida(Nullable<int> pK_IdConceptoPartida, string cT_User, ObjectParameter error)
        {
            var pK_IdConceptoPartidaParameter = pK_IdConceptoPartida.HasValue ?
                new ObjectParameter("PK_IdConceptoPartida", pK_IdConceptoPartida) :
                new ObjectParameter("PK_IdConceptoPartida", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_ConceptoPartida", pK_IdConceptoPartidaParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_FlujoActividad(Nullable<int> pK_IdFlujoActividad, string cT_User, ObjectParameter error)
        {
            var pK_IdFlujoActividadParameter = pK_IdFlujoActividad.HasValue ?
                new ObjectParameter("PK_IdFlujoActividad", pK_IdFlujoActividad) :
                new ObjectParameter("PK_IdFlujoActividad", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_FlujoActividad", pK_IdFlujoActividadParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_FlujoAlcance(Nullable<int> pK_IdFlujoAlcance, string cT_User, ObjectParameter error)
        {
            var pK_IdFlujoAlcanceParameter = pK_IdFlujoAlcance.HasValue ?
                new ObjectParameter("PK_IdFlujoAlcance", pK_IdFlujoAlcance) :
                new ObjectParameter("PK_IdFlujoAlcance", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_FlujoAlcance", pK_IdFlujoAlcanceParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_FlujoCampania(Nullable<int> pK_IdFlujoCampania, string cT_User, ObjectParameter error)
        {
            var pK_IdFlujoCampaniaParameter = pK_IdFlujoCampania.HasValue ?
                new ObjectParameter("PK_IdFlujoCampania", pK_IdFlujoCampania) :
                new ObjectParameter("PK_IdFlujoCampania", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_FlujoCampania", pK_IdFlujoCampaniaParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_Partida(Nullable<int> pK_IdPartida, string cT_User, ObjectParameter error)
        {
            var pK_IdPartidaParameter = pK_IdPartida.HasValue ?
                new ObjectParameter("PK_IdPartida", pK_IdPartida) :
                new ObjectParameter("PK_IdPartida", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_Partida", pK_IdPartidaParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_StatusActividad(Nullable<int> pK_IdStatusActividad, string cT_User, ObjectParameter error)
        {
            var pK_IdStatusActividadParameter = pK_IdStatusActividad.HasValue ?
                new ObjectParameter("PK_IdStatusActividad", pK_IdStatusActividad) :
                new ObjectParameter("PK_IdStatusActividad", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_StatusActividad", pK_IdStatusActividadParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_StatusAlcance(Nullable<int> pK_IdStatusAlcance, string cT_User, ObjectParameter error)
        {
            var pK_IdStatusAlcanceParameter = pK_IdStatusAlcance.HasValue ?
                new ObjectParameter("PK_IdStatusAlcance", pK_IdStatusAlcance) :
                new ObjectParameter("PK_IdStatusAlcance", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_StatusAlcance", pK_IdStatusAlcanceParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_StatusCampania(Nullable<int> pK_IdStatusCampania, string cT_User, ObjectParameter error)
        {
            var pK_IdStatusCampaniaParameter = pK_IdStatusCampania.HasValue ?
                new ObjectParameter("PK_IdStatusCampania", pK_IdStatusCampania) :
                new ObjectParameter("PK_IdStatusCampania", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_StatusCampania", pK_IdStatusCampaniaParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_TipoDeBien(Nullable<int> pK_IdTipoDeBien, string cT_User, ObjectParameter error)
        {
            var pK_IdTipoDeBienParameter = pK_IdTipoDeBien.HasValue ?
                new ObjectParameter("PK_IdTipoDeBien", pK_IdTipoDeBien) :
                new ObjectParameter("PK_IdTipoDeBien", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_TipoDeBien", pK_IdTipoDeBienParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_CapituloPartida(Nullable<int> pK_IdCapituloPartida, string cT_User, ObjectParameter error)
        {
            var pK_IdCapituloPartidaParameter = pK_IdCapituloPartida.HasValue ?
                new ObjectParameter("PK_IdCapituloPartida", pK_IdCapituloPartida) :
                new ObjectParameter("PK_IdCapituloPartida", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_CapituloPartida", pK_IdCapituloPartidaParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_Persona(Nullable<int> pK_IdPersona, string cT_User, ObjectParameter error)
        {
            var pK_IdPersonaParameter = pK_IdPersona.HasValue ?
                new ObjectParameter("PK_IdPersona", pK_IdPersona) :
                new ObjectParameter("PK_IdPersona", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_Persona", pK_IdPersonaParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_Campania(Nullable<int> pK_IdCampania, string cT_User, ObjectParameter error)
        {
            var pK_IdCampaniaParameter = pK_IdCampania.HasValue ?
                new ObjectParameter("PK_IdCampania", pK_IdCampania) :
                new ObjectParameter("PK_IdCampania", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_Campania", pK_IdCampaniaParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_GastoOp(Nullable<int> pK_IdGastoOp, string cT_User, ObjectParameter error)
        {
            var pK_IdGastoOpParameter = pK_IdGastoOp.HasValue ?
                new ObjectParameter("PK_IdGastoOp", pK_IdGastoOp) :
                new ObjectParameter("PK_IdGastoOp", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_GastoOp", pK_IdGastoOpParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_GastoTransv(Nullable<int> pK_IdGastoTransv, string cT_User, ObjectParameter error)
        {
            var pK_IdGastoTransvParameter = pK_IdGastoTransv.HasValue ?
                new ObjectParameter("PK_IdGastoTransv", pK_IdGastoTransv) :
                new ObjectParameter("PK_IdGastoTransv", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_GastoTransv", pK_IdGastoTransvParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_Inventario(Nullable<int> pK_IdInventario, string cT_User, ObjectParameter error)
        {
            var pK_IdInventarioParameter = pK_IdInventario.HasValue ?
                new ObjectParameter("PK_IdInventario", pK_IdInventario) :
                new ObjectParameter("PK_IdInventario", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_Inventario", pK_IdInventarioParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_PEFXEstado(Nullable<int> pK_IdPEFXEstado, string cT_User, ObjectParameter error)
        {
            var pK_IdPEFXEstadoParameter = pK_IdPEFXEstado.HasValue ?
                new ObjectParameter("PK_IdPEFXEstado", pK_IdPEFXEstado) :
                new ObjectParameter("PK_IdPEFXEstado", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_PEFXEstado", pK_IdPEFXEstadoParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_Vigencia(Nullable<int> pK_IdVigencia, string cT_User, ObjectParameter error)
        {
            var pK_IdVigenciaParameter = pK_IdVigencia.HasValue ?
                new ObjectParameter("PK_IdVigencia", pK_IdVigencia) :
                new ObjectParameter("PK_IdVigencia", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_Vigencia", pK_IdVigenciaParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_AccionXCampania(Nullable<int> pK_IdAccionXCampania, string cT_User, ObjectParameter error)
        {
            var pK_IdAccionXCampaniaParameter = pK_IdAccionXCampania.HasValue ?
                new ObjectParameter("PK_IdAccionXCampania", pK_IdAccionXCampania) :
                new ObjectParameter("PK_IdAccionXCampania", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_AccionXCampania", pK_IdAccionXCampaniaParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_AtendidoSA(Nullable<int> pK_IdAtendidoSA, string cT_User, ObjectParameter error)
        {
            var pK_IdAtendidoSAParameter = pK_IdAtendidoSA.HasValue ?
                new ObjectParameter("PK_IdAtendidoSA", pK_IdAtendidoSA) :
                new ObjectParameter("PK_IdAtendidoSA", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_AtendidoSA", pK_IdAtendidoSAParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_AtendidoSV(Nullable<int> pK_IdAtendidoSV, string cT_User, ObjectParameter error)
        {
            var pK_IdAtendidoSVParameter = pK_IdAtendidoSV.HasValue ?
                new ObjectParameter("PK_IdAtendidoSV", pK_IdAtendidoSV) :
                new ObjectParameter("PK_IdAtendidoSV", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_AtendidoSV", pK_IdAtendidoSVParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_ImportanciaCultivoSV(Nullable<int> pK_IdImportanciaCultivoSV, string cT_User, ObjectParameter error)
        {
            var pK_IdImportanciaCultivoSVParameter = pK_IdImportanciaCultivoSV.HasValue ?
                new ObjectParameter("PK_IdImportanciaCultivoSV", pK_IdImportanciaCultivoSV) :
                new ObjectParameter("PK_IdImportanciaCultivoSV", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_ImportanciaCultivoSV", pK_IdImportanciaCultivoSVParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_ImportanciaEconomicaSA(Nullable<int> pK_IdImportanciaEconomicaSA, string cT_User, ObjectParameter error)
        {
            var pK_IdImportanciaEconomicaSAParameter = pK_IdImportanciaEconomicaSA.HasValue ?
                new ObjectParameter("PK_IdImportanciaEconomicaSA", pK_IdImportanciaEconomicaSA) :
                new ObjectParameter("PK_IdImportanciaEconomicaSA", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_ImportanciaEconomicaSA", pK_IdImportanciaEconomicaSAParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_ImportanciaEnfermedadSA(Nullable<int> pK_IdImportanciaEnfermedadSA, string cT_User, ObjectParameter error)
        {
            var pK_IdImportanciaEnfermedadSAParameter = pK_IdImportanciaEnfermedadSA.HasValue ?
                new ObjectParameter("PK_IdImportanciaEnfermedadSA", pK_IdImportanciaEnfermedadSA) :
                new ObjectParameter("PK_IdImportanciaEnfermedadSA", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_ImportanciaEnfermedadSA", pK_IdImportanciaEnfermedadSAParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_ImportanciaPIVMov(Nullable<int> pK_IdImportanciaPIVMov, string cT_User, ObjectParameter error)
        {
            var pK_IdImportanciaPIVMovParameter = pK_IdImportanciaPIVMov.HasValue ?
                new ObjectParameter("PK_IdImportanciaPIVMov", pK_IdImportanciaPIVMov) :
                new ObjectParameter("PK_IdImportanciaPIVMov", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_ImportanciaPIVMov", pK_IdImportanciaPIVMovParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_ImportanciaPlagaSV(Nullable<int> pK_IdImportanciaPlagaSV, string cT_User, ObjectParameter error)
        {
            var pK_IdImportanciaPlagaSVParameter = pK_IdImportanciaPlagaSV.HasValue ?
                new ObjectParameter("PK_IdImportanciaPlagaSV", pK_IdImportanciaPlagaSV) :
                new ObjectParameter("PK_IdImportanciaPlagaSV", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_ImportanciaPlagaSV", pK_IdImportanciaPlagaSVParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_InoCompSA(Nullable<int> pK_IdInoCompSA, string cT_User, ObjectParameter error)
        {
            var pK_IdInoCompSAParameter = pK_IdInoCompSA.HasValue ?
                new ObjectParameter("PK_IdInoCompSA", pK_IdInoCompSA) :
                new ObjectParameter("PK_IdInoCompSA", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_InoCompSA", pK_IdInoCompSAParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_InoCompSAC(Nullable<int> pK_IdInoCompSAC, string cT_User, ObjectParameter error)
        {
            var pK_IdInoCompSACParameter = pK_IdInoCompSAC.HasValue ?
                new ObjectParameter("PK_IdInoCompSAC", pK_IdInoCompSAC) :
                new ObjectParameter("PK_IdInoCompSAC", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_InoCompSAC", pK_IdInoCompSACParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_InoCompSV(Nullable<int> pK_IdInoCompSV, string cT_User, ObjectParameter error)
        {
            var pK_IdInoCompSVParameter = pK_IdInoCompSV.HasValue ?
                new ObjectParameter("PK_IdInoCompSV", pK_IdInoCompSV) :
                new ObjectParameter("PK_IdInoCompSV", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_InoCompSV", pK_IdInoCompSVParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_InoImportanciaSA(Nullable<int> pK_IdInoImportanciaSA, string cT_User, ObjectParameter error)
        {
            var pK_IdInoImportanciaSAParameter = pK_IdInoImportanciaSA.HasValue ?
                new ObjectParameter("PK_IdInoImportanciaSA", pK_IdInoImportanciaSA) :
                new ObjectParameter("PK_IdInoImportanciaSA", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_InoImportanciaSA", pK_IdInoImportanciaSAParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_InoImportanciaSAC(Nullable<int> pK_IdInoImportanciaSAC, string cT_User, ObjectParameter error)
        {
            var pK_IdInoImportanciaSACParameter = pK_IdInoImportanciaSAC.HasValue ?
                new ObjectParameter("PK_IdInoImportanciaSAC", pK_IdInoImportanciaSAC) :
                new ObjectParameter("PK_IdInoImportanciaSAC", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_InoImportanciaSAC", pK_IdInoImportanciaSACParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_InoImportanciaSV(Nullable<int> pK_IdInoImportanciaSV, string cT_User, ObjectParameter error)
        {
            var pK_IdInoImportanciaSVParameter = pK_IdInoImportanciaSV.HasValue ?
                new ObjectParameter("PK_IdInoImportanciaSV", pK_IdInoImportanciaSV) :
                new ObjectParameter("PK_IdInoImportanciaSV", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_InoImportanciaSV", pK_IdInoImportanciaSVParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_InoUnidadesCertSA(Nullable<int> pK_IdInoUnidadesCertSA, string cT_User, ObjectParameter error)
        {
            var pK_IdInoUnidadesCertSAParameter = pK_IdInoUnidadesCertSA.HasValue ?
                new ObjectParameter("PK_IdInoUnidadesCertSA", pK_IdInoUnidadesCertSA) :
                new ObjectParameter("PK_IdInoUnidadesCertSA", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_InoUnidadesCertSA", pK_IdInoUnidadesCertSAParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_InoUnidadesCertSAC(Nullable<int> pK_IdInoUnidadesCertSAC, string cT_User, ObjectParameter error)
        {
            var pK_IdInoUnidadesCertSACParameter = pK_IdInoUnidadesCertSAC.HasValue ?
                new ObjectParameter("PK_IdInoUnidadesCertSAC", pK_IdInoUnidadesCertSAC) :
                new ObjectParameter("PK_IdInoUnidadesCertSAC", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_InoUnidadesCertSAC", pK_IdInoUnidadesCertSACParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_InoUnidadesCertSV(Nullable<int> pK_IdInoUnidadesCertSV, string cT_User, ObjectParameter error)
        {
            var pK_IdInoUnidadesCertSVParameter = pK_IdInoUnidadesCertSV.HasValue ?
                new ObjectParameter("PK_IdInoUnidadesCertSV", pK_IdInoUnidadesCertSV) :
                new ObjectParameter("PK_IdInoUnidadesCertSV", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_InoUnidadesCertSV", pK_IdInoUnidadesCertSVParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_RepActividad(Nullable<int> pK_IdRepActividad, string cT_User, ObjectParameter error)
        {
            var pK_IdRepActividadParameter = pK_IdRepActividad.HasValue ?
                new ObjectParameter("PK_IdRepActividad", pK_IdRepActividad) :
                new ObjectParameter("PK_IdRepActividad", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_RepActividad", pK_IdRepActividadParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_RepAdquisicion(Nullable<int> pK_IdRepAdquisicion, string cT_User, ObjectParameter error)
        {
            var pK_IdRepAdquisicionParameter = pK_IdRepAdquisicion.HasValue ?
                new ObjectParameter("PK_IdRepAdquisicion", pK_IdRepAdquisicion) :
                new ObjectParameter("PK_IdRepAdquisicion", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_RepAdquisicion", pK_IdRepAdquisicionParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_RepGasto(Nullable<int> pK_IdRepGasto, string cT_User, ObjectParameter error)
        {
            var pK_IdRepGastoParameter = pK_IdRepGasto.HasValue ?
                new ObjectParameter("PK_IdRepGasto", pK_IdRepGasto) :
                new ObjectParameter("PK_IdRepGasto", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_RepGasto", pK_IdRepGastoParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_Actividad(Nullable<int> pK_IdActividad, string cT_User, ObjectParameter error)
        {
            var pK_IdActividadParameter = pK_IdActividad.HasValue ?
                new ObjectParameter("PK_IdActividad", pK_IdActividad) :
                new ObjectParameter("PK_IdActividad", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_Actividad", pK_IdActividadParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_ActividadXAccion(Nullable<int> pK_IdActividadXAccion, string cT_User, ObjectParameter error)
        {
            var pK_IdActividadXAccionParameter = pK_IdActividadXAccion.HasValue ?
                new ObjectParameter("PK_IdActividadXAccion", pK_IdActividadXAccion) :
                new ObjectParameter("PK_IdActividadXAccion", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_ActividadXAccion", pK_IdActividadXAccionParameter, cT_UserParameter, error);
        }
    
        public virtual int SP_DELETE_Instalacion(Nullable<int> pK_IdInstalacion, string cT_User, ObjectParameter error)
        {
            var pK_IdInstalacionParameter = pK_IdInstalacion.HasValue ?
                new ObjectParameter("PK_IdInstalacion", pK_IdInstalacion) :
                new ObjectParameter("PK_IdInstalacion", typeof(int));
    
            var cT_UserParameter = cT_User != null ?
                new ObjectParameter("CT_User", cT_User) :
                new ObjectParameter("CT_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_Instalacion", pK_IdInstalacionParameter, cT_UserParameter, error);
        }
    
        [DbFunction("DB_SENASICAEntities", "PresByCampania")]
        public virtual IQueryable<PresByCampania_Result> PresByCampania(Nullable<int> idCampania)
        {
            var idCampaniaParameter = idCampania.HasValue ?
                new ObjectParameter("IdCampania", idCampania) :
                new ObjectParameter("IdCampania", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<PresByCampania_Result>("[DB_SENASICAEntities].[PresByCampania](@IdCampania)", idCampaniaParameter);
        }
    }
}
