//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovRepRecursoFed
    {
        public int Pk_IdMovRepRecursoFed { get; set; }
        public int Identificador { get; set; }
        public int Fk_IdAnio { get; set; }
        public int Fk_IdEstado { get; set; }
        public Nullable<int> Fk_IdCampaniaOrigen { get; set; }
        public string NombreCampaniaOrigen { get; set; }
        public Nullable<decimal> RecFedOrigen { get; set; }
        public Nullable<decimal> RecSol_FedOrigen { get; set; }
        public Nullable<decimal> Rec_GastadoOrigen { get; set; }
        public Nullable<decimal> SaldoDisponibleOrigen { get; set; }
        public int Fk_IdCampaniaDestino { get; set; }
        public string NombreCampaniaDestino { get; set; }
        public Nullable<decimal> RecFedDestino { get; set; }
        public Nullable<decimal> RecSol_FedDestino { get; set; }
        public Nullable<decimal> Rec_GastadoDestino { get; set; }
        public Nullable<decimal> SaldoDisponibleDestino { get; set; }
        public Nullable<int> Fk_IdMotivoIncremento { get; set; }
        public decimal MontoTransferido { get; set; }
        public System.DateTime FechaMovimiento { get; set; }
        public bool esHistorico { get; set; }
    
        public virtual MotivoIncremento MotivoIncremento { get; set; }
    }
}
