//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MunicipiosGeo
    {
        public int CVE_ENT { get; set; }
        public int CVE_MUN { get; set; }
        public string NOM_MUN { get; set; }
        public System.Data.Entity.Spatial.DbGeometry GEOM { get; set; }
        public int id { get; set; }
    }
}
