//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipio
    {
        public Municipio()
        {
            this.Mov_ImportanciaPIV = new HashSet<Mov_ImportanciaPIV>();
            this.SA_Atendido = new HashSet<SA_Atendido>();
            this.SA_ImportanciaEnfermedad = new HashSet<SA_ImportanciaEnfermedad>();
            this.SACImportanciaEnfermedads = new HashSet<SACImportanciaEnfermedad>();
            this.SA_Poblacion = new HashSet<SA_Poblacion>();
            this.SVAtendidoes = new HashSet<SVAtendido>();
            this.SVImportanciaCultivoes = new HashSet<SVImportanciaCultivo>();
            this.SVImportanciaPlagas = new HashSet<SVImportanciaPlaga>();
            this.InoCompSAs = new HashSet<InoCompSA>();
            this.InoCompSACs = new HashSet<InoCompSAC>();
            this.InoCompSVs = new HashSet<InoCompSV>();
            this.InoImportanciaSAs = new HashSet<InoImportanciaSA>();
            this.InoImportanciaSACs = new HashSet<InoImportanciaSAC>();
            this.InoImportanciaSVs = new HashSet<InoImportanciaSV>();
            this.InoUnidadesCertSAs = new HashSet<InoUnidadesCertSA>();
            this.InoUnidadesCertSACs = new HashSet<InoUnidadesCertSAC>();
            this.InoUnidadesCertSVs = new HashSet<InoUnidadesCertSV>();
            this.Proveedors = new HashSet<Proveedor>();
            this.SACImportanciaCultivoes = new HashSet<SACImportanciaCultivo>();
            this.SAC_Atendido = new HashSet<SAC_Atendido>();
            this.Productors = new HashSet<Productor>();
            this.Mov_ImportanciaProg = new HashSet<Mov_ImportanciaProg>();
            this.AtendidoSAs = new HashSet<AtendidoSA>();
            this.ImportanciaCultivoSVs = new HashSet<ImportanciaCultivoSV>();
            this.ImportanciaEconomicaSAs = new HashSet<ImportanciaEconomicaSA>();
            this.ImportanciaPlagaSVs = new HashSet<ImportanciaPlagaSV>();
            this.AtendidoSACs = new HashSet<AtendidoSAC>();
            this.ImportanciaCultivoSACs = new HashSet<ImportanciaCultivoSAC>();
            this.ImportanciaEnfermedadSACs = new HashSet<ImportanciaEnfermedadSAC>();
            this.ImportanciaEnfermedadSAs = new HashSet<ImportanciaEnfermedadSA>();
            this.Personas = new HashSet<Persona>();
            this.AtendidoSVs = new HashSet<AtendidoSV>();
            this.UnidadEjecutoras = new HashSet<UnidadEjecutora>();
            this.AtendidoSA_Repro = new HashSet<AtendidoSA_Repro>();
            this.AtendidoSAC_Repro = new HashSet<AtendidoSAC_Repro>();
            this.AtendidoSV_Repro = new HashSet<AtendidoSV_Repro>();
            this.ImportanciaCultivoSAC_Repro = new HashSet<ImportanciaCultivoSAC_Repro>();
            this.ImportanciaCultivoSV_Repro = new HashSet<ImportanciaCultivoSV_Repro>();
            this.ImportanciaEconomicaSA_Repro = new HashSet<ImportanciaEconomicaSA_Repro>();
            this.ImportanciaEnfermedadSA_Repro = new HashSet<ImportanciaEnfermedadSA_Repro>();
            this.ImportanciaEnfermedadSAC_Repro = new HashSet<ImportanciaEnfermedadSAC_Repro>();
            this.ImportanciaPlagaSV_Repro = new HashSet<ImportanciaPlagaSV_Repro>();
        }
    
        public int Pk_IdMunicipio { get; set; }
        public Nullable<int> Fk_IdEstado__SIS { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Mov_ImportanciaPIV> Mov_ImportanciaPIV { get; set; }
        public virtual ICollection<SA_Atendido> SA_Atendido { get; set; }
        public virtual ICollection<SA_ImportanciaEnfermedad> SA_ImportanciaEnfermedad { get; set; }
        public virtual ICollection<SACImportanciaEnfermedad> SACImportanciaEnfermedads { get; set; }
        public virtual ICollection<SA_Poblacion> SA_Poblacion { get; set; }
        public virtual ICollection<SVAtendido> SVAtendidoes { get; set; }
        public virtual ICollection<SVImportanciaCultivo> SVImportanciaCultivoes { get; set; }
        public virtual ICollection<SVImportanciaPlaga> SVImportanciaPlagas { get; set; }
        public virtual ICollection<InoCompSA> InoCompSAs { get; set; }
        public virtual ICollection<InoCompSAC> InoCompSACs { get; set; }
        public virtual ICollection<InoCompSV> InoCompSVs { get; set; }
        public virtual ICollection<InoImportanciaSA> InoImportanciaSAs { get; set; }
        public virtual ICollection<InoImportanciaSAC> InoImportanciaSACs { get; set; }
        public virtual ICollection<InoImportanciaSV> InoImportanciaSVs { get; set; }
        public virtual ICollection<InoUnidadesCertSA> InoUnidadesCertSAs { get; set; }
        public virtual ICollection<InoUnidadesCertSAC> InoUnidadesCertSACs { get; set; }
        public virtual ICollection<InoUnidadesCertSV> InoUnidadesCertSVs { get; set; }
        public virtual ICollection<Proveedor> Proveedors { get; set; }
        public virtual ICollection<SACImportanciaCultivo> SACImportanciaCultivoes { get; set; }
        public virtual ICollection<SAC_Atendido> SAC_Atendido { get; set; }
        public virtual ICollection<Productor> Productors { get; set; }
        public virtual ICollection<Mov_ImportanciaProg> Mov_ImportanciaProg { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual ICollection<AtendidoSA> AtendidoSAs { get; set; }
        public virtual ICollection<ImportanciaCultivoSV> ImportanciaCultivoSVs { get; set; }
        public virtual ICollection<ImportanciaEconomicaSA> ImportanciaEconomicaSAs { get; set; }
        public virtual ICollection<ImportanciaPlagaSV> ImportanciaPlagaSVs { get; set; }
        public virtual ICollection<AtendidoSAC> AtendidoSACs { get; set; }
        public virtual ICollection<ImportanciaCultivoSAC> ImportanciaCultivoSACs { get; set; }
        public virtual ICollection<ImportanciaEnfermedadSAC> ImportanciaEnfermedadSACs { get; set; }
        public virtual ICollection<ImportanciaEnfermedadSA> ImportanciaEnfermedadSAs { get; set; }
        public virtual ICollection<Persona> Personas { get; set; }
        public virtual ICollection<AtendidoSV> AtendidoSVs { get; set; }
        public virtual ICollection<UnidadEjecutora> UnidadEjecutoras { get; set; }
        public virtual ICollection<AtendidoSA_Repro> AtendidoSA_Repro { get; set; }
        public virtual ICollection<AtendidoSAC_Repro> AtendidoSAC_Repro { get; set; }
        public virtual ICollection<AtendidoSV_Repro> AtendidoSV_Repro { get; set; }
        public virtual ICollection<ImportanciaCultivoSAC_Repro> ImportanciaCultivoSAC_Repro { get; set; }
        public virtual ICollection<ImportanciaCultivoSV_Repro> ImportanciaCultivoSV_Repro { get; set; }
        public virtual ICollection<ImportanciaEconomicaSA_Repro> ImportanciaEconomicaSA_Repro { get; set; }
        public virtual ICollection<ImportanciaEnfermedadSA_Repro> ImportanciaEnfermedadSA_Repro { get; set; }
        public virtual ICollection<ImportanciaEnfermedadSAC_Repro> ImportanciaEnfermedadSAC_Repro { get; set; }
        public virtual ICollection<ImportanciaPlagaSV_Repro> ImportanciaPlagaSV_Repro { get; set; }
    }
}
