//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NecesidadXAccion
    {
        public int Pk_IdNecesidadXAccion { get; set; }
        public int Fk_IdAccionXCampania { get; set; }
        public int Fk_IdBienOServ { get; set; }
        public int Fk_IdUnidadDeMedida { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> Cant_Ene { get; set; }
        public Nullable<double> Cant_Feb { get; set; }
        public Nullable<double> Cant_Mar { get; set; }
        public Nullable<double> Cant_Abr { get; set; }
        public Nullable<double> Cant_May { get; set; }
        public Nullable<double> Cant_Jun { get; set; }
        public Nullable<double> Cant_Jul { get; set; }
        public Nullable<double> Cant_Ago { get; set; }
        public Nullable<double> Cant_Sep { get; set; }
        public Nullable<double> Cant_Oct { get; set; }
        public Nullable<double> Cant_Nov { get; set; }
        public Nullable<double> Cant_Dic { get; set; }
        public Nullable<double> Cant_Anual { get; set; }
        public string Justificacion { get; set; }
        public Nullable<double> imp_Ene { get; set; }
        public Nullable<double> imp_Feb { get; set; }
        public Nullable<double> imp_Mar { get; set; }
        public Nullable<double> imp_Abr { get; set; }
        public Nullable<double> imp_May { get; set; }
        public Nullable<double> imp_Jun { get; set; }
        public Nullable<double> imp_Jul { get; set; }
        public Nullable<double> imp_Ago { get; set; }
        public Nullable<double> imp_Sep { get; set; }
        public Nullable<double> imp_Oct { get; set; }
        public Nullable<double> imp_Nov { get; set; }
        public Nullable<double> imp_Dic { get; set; }
        public Nullable<double> imp_Anual { get; set; }
        public Nullable<double> RecFed { get; set; }
        public Nullable<double> RecEst { get; set; }
        public Nullable<double> RecProp { get; set; }
    
        public virtual UnidadDeMedida UnidadDeMedida { get; set; }
        public virtual AccionXCampania AccionXCampania { get; set; }
        public virtual BienOServ BienOServ { get; set; }
    }
}
