//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        public Partida()
        {
            this.TipoDeBiens = new HashSet<TipoDeBien>();
        }
    
        public int Pk_IdPartida { get; set; }
        public int Fk_IdConceptoPartida__SIS { get; set; }
        public string Nombre { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
        public int Fk_IdAnio { get; set; }
    
        public virtual ConceptoPartida ConceptoPartida { get; set; }
        public virtual ICollection<TipoDeBien> TipoDeBiens { get; set; }
        public virtual Anio Anio { get; set; }
    }
}
