//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEFXEstado
    {
        public int Pk_IdPEFXEstado { get; set; }
        public int FK_IdAnio { get; set; }
        public int FK_IdEstado { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> SistemaInform { get; set; }
        public Nullable<decimal> Capacitacion { get; set; }
        public Nullable<decimal> Divulgacion { get; set; }
        public Nullable<decimal> Emergencias { get; set; }
        public Nullable<decimal> Comp_CampFitoZoo { get; set; }
        public Nullable<decimal> Comp_IAAP { get; set; }
        public Nullable<decimal> Comp_InspVig { get; set; }
        public Nullable<decimal> Comp_VigCuarentenaria { get; set; }
        public Nullable<decimal> GtoInversion { get; set; }
        public Nullable<decimal> GtoOperacion { get; set; }
        public Nullable<decimal> Componentes { get; set; }
        public Nullable<bool> PresupuestoCerrado { get; set; }
        public Nullable<decimal> SistemaInform_Est { get; set; }
        public Nullable<decimal> Capacitacion_Est { get; set; }
        public Nullable<decimal> Divulgacion_Est { get; set; }
        public Nullable<decimal> Emergencias_Est { get; set; }
        public Nullable<decimal> GtoOperacion_Est { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
        public Nullable<decimal> UISEstatales { get; set; }
        public Nullable<decimal> Gtotransv { get; set; }
        public Nullable<decimal> InteligenciaSanitaria_Est { get; set; }
    
        public virtual Anio Anio { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
