//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.CertificadoPersonas = new HashSet<CertificadoPersona>();
            this.AccionXCampanias = new HashSet<AccionXCampania>();
            this.Accions = new HashSet<Accion>();
            this.AccionXCampania_Repro = new HashSet<AccionXCampania_Repro>();
            this.Campania_Repro = new HashSet<Campania_Repro>();
            this.RepActividads = new HashSet<RepActividad>();
            this.ActividadXAccion_Repro = new HashSet<ActividadXAccion_Repro>();
            this.Campanias = new HashSet<Campania>();
            this.Actividads = new HashSet<Actividad>();
            this.ActividadXAccions = new HashSet<ActividadXAccion>();
        }
    
        public int Pk_IdPersona { get; set; }
        public int Fk_IdUnidadEjecutora__UE { get; set; }
        public string Ap_Paterno { get; set; }
        public string Ap_Materno { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Colonia { get; set; }
        public int Fk_IdMunicipioPersona__SIS { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public System.Data.Entity.Spatial.DbGeography Ubicacion { get; set; }
        public Nullable<int> Fk_IdCargo { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
        public string NoCedulaProfesional { get; set; }
        public string CodigoPostal { get; set; }
        public string Profesion { get; set; }
        public string Especialidad { get; set; }
        public string Experiencia { get; set; }
        public string Certificaciones { get; set; }
        public string NoLicenciaManejo { get; set; }
        public string NombreCompleto { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
        public bool esActivo { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual ICollection<CertificadoPersona> CertificadoPersonas { get; set; }
        public virtual Municipio Municipio { get; set; }
        public virtual ICollection<AccionXCampania> AccionXCampanias { get; set; }
        public virtual ICollection<Accion> Accions { get; set; }
        public virtual UnidadEjecutora UnidadEjecutora { get; set; }
        public virtual ICollection<AccionXCampania_Repro> AccionXCampania_Repro { get; set; }
        public virtual ICollection<Campania_Repro> Campania_Repro { get; set; }
        public virtual ICollection<RepActividad> RepActividads { get; set; }
        public virtual ICollection<ActividadXAccion_Repro> ActividadXAccion_Repro { get; set; }
        public virtual ICollection<Campania> Campanias { get; set; }
        public virtual ICollection<Actividad> Actividads { get; set; }
        public virtual ICollection<ActividadXAccion> ActividadXAccions { get; set; }
    }
}
