//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PorcentajeXDireccionGeneral
    {
        public PorcentajeXDireccionGeneral()
        {
            this.PresupuestoXEstadoes = new HashSet<PresupuestoXEstado>();
        }
    
        public int Pk_IdPorcentajeXDireccionGeneral { get; set; }
        public int FK_IdUnidadResponsable { get; set; }
        public int FK_IdAnio { get; set; }
        public double PresupuestoAsignado { get; set; }
        public bool PresupuestoCerrado { get; set; }
    
        public virtual Anio Anio { get; set; }
        public virtual UnidadResponsable UnidadResponsable { get; set; }
        public virtual ICollection<PresupuestoXEstado> PresupuestoXEstadoes { get; set; }
    }
}
