//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predio
    {
        public int Pk_IdPredio { get; set; }
        public int Fk_IdProductor__UE { get; set; }
        public string NombrePredio { get; set; }
        public System.Data.Entity.Spatial.DbGeography Poligono { get; set; }
    
        public virtual SubPredio SubPredio { get; set; }
        public virtual Productor Productor { get; set; }
    }
}
