//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresXAUR
    {
        public int Pk_IdPresXAUR { get; set; }
        public Nullable<int> Fk_IdEstado { get; set; }
        public Nullable<int> Fk_IdAnio { get; set; }
        public Nullable<decimal> DGSV { get; set; }
        public Nullable<decimal> DGSA { get; set; }
        public Nullable<decimal> DGIF { get; set; }
        public Nullable<decimal> DGIAAP { get; set; }
        public Nullable<decimal> totalEstado { get; set; }
    
        public virtual Anio Anio { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
