//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivilegiosXRol
    {
        public int Pk_IdPrivilegiosXRol { get; set; }
        public Nullable<int> Fk_IdRol__SIS { get; set; }
        public Nullable<int> Fk_IdPantalla__SIS { get; set; }
        public bool Lectura { get; set; }
        public bool Escritura { get; set; }
        public bool VisualizaReporte { get; set; }
    
        public virtual Pantalla Pantalla { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
