//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productor
    {
        public Productor()
        {
            this.Predios = new HashSet<Predio>();
            this.Beneficiarios = new HashSet<Beneficiario>();
        }
    
        public int Pk_IdProductor { get; set; }
        public string RazonSocial { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Colonia { get; set; }
        public int Fk_IdEstado__SIS { get; set; }
        public int Fk_IdMunicipio__SIS { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public System.Data.Entity.Spatial.DbGeography Ubicacion { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
    
        public virtual ICollection<Predio> Predios { get; set; }
        public virtual Municipio Municipio { get; set; }
        public virtual ICollection<Beneficiario> Beneficiarios { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
