//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoPresupuesto
    {
        public ProyectoPresupuesto()
        {
            this.Campania_Repro = new HashSet<Campania_Repro>();
            this.ProgramasGastosTransversales = new HashSet<ProgramasGastosTransversale>();
            this.Campanias = new HashSet<Campania>();
            this.TesofeDetalles = new HashSet<TesofeDetalle>();
        }
    
        public int Pk_IdProyectoPresupuesto { get; set; }
        public int Fk_IdProyectoAutorizado { get; set; }
        public int Fk_IdEstado { get; set; }
        public int Fk_IdAnio { get; set; }
        public Nullable<decimal> RF_Ene { get; set; }
        public Nullable<decimal> RF_Feb { get; set; }
        public Nullable<decimal> RF_Mar { get; set; }
        public Nullable<decimal> RF_Abr { get; set; }
        public Nullable<decimal> RF_May { get; set; }
        public Nullable<decimal> RF_Jun { get; set; }
        public Nullable<decimal> RF_Jul { get; set; }
        public Nullable<decimal> RF_Ago { get; set; }
        public Nullable<decimal> RF_Sep { get; set; }
        public Nullable<decimal> RF_Oct { get; set; }
        public Nullable<decimal> RF_Nov { get; set; }
        public Nullable<decimal> RF_Dic { get; set; }
        public Nullable<decimal> RE_Ene { get; set; }
        public Nullable<decimal> RE_Feb { get; set; }
        public Nullable<decimal> RE_Mar { get; set; }
        public Nullable<decimal> RE_Abr { get; set; }
        public Nullable<decimal> RE_May { get; set; }
        public Nullable<decimal> RE_Jun { get; set; }
        public Nullable<decimal> RE_Jul { get; set; }
        public Nullable<decimal> RE_Ago { get; set; }
        public Nullable<decimal> RE_Sep { get; set; }
        public Nullable<decimal> RE_Oct { get; set; }
        public Nullable<decimal> RE_Nov { get; set; }
        public Nullable<decimal> RE_Dic { get; set; }
        public Nullable<decimal> RP_Ene { get; set; }
        public Nullable<decimal> RP_Feb { get; set; }
        public Nullable<decimal> RP_Mar { get; set; }
        public Nullable<decimal> RP_Abr { get; set; }
        public Nullable<decimal> RP_May { get; set; }
        public Nullable<decimal> RP_Jun { get; set; }
        public Nullable<decimal> RP_Jul { get; set; }
        public Nullable<decimal> RP_Ago { get; set; }
        public Nullable<decimal> RP_Sep { get; set; }
        public Nullable<decimal> RP_Oct { get; set; }
        public Nullable<decimal> RP_Nov { get; set; }
        public Nullable<decimal> RP_Dic { get; set; }
        public Nullable<bool> CierraPresupuesto { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
        public Nullable<decimal> RF_Anual { get; set; }
        public Nullable<decimal> RE_Anual { get; set; }
        public Nullable<decimal> RP_Anual { get; set; }
        public Nullable<int> Fk_IdUnidadEjecutora { get; set; }
        public Nullable<int> Fk_IdUnidadResponsable { get; set; }
        public Nullable<int> Fk_IdTipoCampania { get; set; }
    
        public virtual Anio Anio { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual UnidadResponsable UnidadResponsable { get; set; }
        public virtual UnidadEjecutora UnidadEjecutora { get; set; }
        public virtual TipoCampania TipoCampania { get; set; }
        public virtual ICollection<Campania_Repro> Campania_Repro { get; set; }
        public virtual ProyectoAutorizado ProyectoAutorizado { get; set; }
        public virtual ICollection<ProgramasGastosTransversale> ProgramasGastosTransversales { get; set; }
        public virtual ICollection<Campania> Campanias { get; set; }
        public virtual ICollection<TesofeDetalle> TesofeDetalles { get; set; }
    }
}
