//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoAutorizado
    {
        public ProyectoAutorizado()
        {
            this.ProyectoPresupuestoes = new HashSet<ProyectoPresupuesto>();
            this.TipoDeAccions = new HashSet<TipoDeAccion>();
        }
    
        public int Pk_IdProyectoAutorizado { get; set; }
        public int Fk_IdSubComponente__SIS { get; set; }
        public int Fk_IdAnio { get; set; }
        public string Nombre { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
    
        public virtual Anio Anio { get; set; }
        public virtual SubComponente SubComponente { get; set; }
        public virtual ICollection<ProyectoPresupuesto> ProyectoPresupuestoes { get; set; }
        public virtual ICollection<TipoDeAccion> TipoDeAccions { get; set; }
    }
}
