//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepActividad
    {
        public RepActividad()
        {
            this.RepGastoes = new HashSet<RepGasto>();
        }
    
        public int Pk_IdRepActividad { get; set; }
        public int Fk_IdActividad { get; set; }
        public int Fk_IdPersona { get; set; }
        public System.DateTime FechaInforme { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string Informe { get; set; }
        public decimal CantidadMetas { get; set; }
        public System.Data.Entity.Spatial.DbGeography Ubicacion { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
        public bool esCerrado { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual ICollection<RepGasto> RepGastoes { get; set; }
        public virtual Actividad Actividad { get; set; }
    }
}
