//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepGasto
    {
        public int Pk_IdRepGasto { get; set; }
        public int Fk_IdRepActividad { get; set; }
        public System.DateTime FechaGasto { get; set; }
        public string Concepto { get; set; }
        public double Importe { get; set; }
        public string Comentario { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
    
        public virtual RepActividad RepActividad { get; set; }
    }
}
