//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_ReprogramacionRecFed : DbContext
    {
        public DB_ReprogramacionRecFed()
            : base("name=DB_ReprogramacionRecFed")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MotivoIncremento> MotivoIncremento { get; set; }
        public virtual DbSet<MovRepRecursoFed> MovRepRecursoFed { get; set; }
        public virtual DbSet<CampaniasXEstado> CampaniasXEstado { get; set; }
    
        public virtual int SP_CleanCampaniaXEstado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CleanCampaniaXEstado");
        }
    
        public virtual int SP_CleanMovRepRecursoFed()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CleanMovRepRecursoFed");
        }
    
        public virtual int SP_RespaldoCampaniasXEstado(Nullable<int> idEstado, Nullable<int> idAnioPres)
        {
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(int));
    
            var idAnioPresParameter = idAnioPres.HasValue ?
                new ObjectParameter("IdAnioPres", idAnioPres) :
                new ObjectParameter("IdAnioPres", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RespaldoCampaniasXEstado", idEstadoParameter, idAnioPresParameter);
        }
    
        public virtual int SP_AgregaElementoReproFed(Nullable<int> identificador, Nullable<int> idCampaniaOrigen, Nullable<int> idCampaniaDestino, Nullable<int> idMotivoIncremento, Nullable<decimal> montoTransferido)
        {
            var identificadorParameter = identificador.HasValue ?
                new ObjectParameter("Identificador", identificador) :
                new ObjectParameter("Identificador", typeof(int));
    
            var idCampaniaOrigenParameter = idCampaniaOrigen.HasValue ?
                new ObjectParameter("IdCampaniaOrigen", idCampaniaOrigen) :
                new ObjectParameter("IdCampaniaOrigen", typeof(int));
    
            var idCampaniaDestinoParameter = idCampaniaDestino.HasValue ?
                new ObjectParameter("IdCampaniaDestino", idCampaniaDestino) :
                new ObjectParameter("IdCampaniaDestino", typeof(int));
    
            var idMotivoIncrementoParameter = idMotivoIncremento.HasValue ?
                new ObjectParameter("IdMotivoIncremento", idMotivoIncremento) :
                new ObjectParameter("IdMotivoIncremento", typeof(int));
    
            var montoTransferidoParameter = montoTransferido.HasValue ?
                new ObjectParameter("MontoTransferido", montoTransferido) :
                new ObjectParameter("MontoTransferido", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AgregaElementoReproFed", identificadorParameter, idCampaniaOrigenParameter, idCampaniaDestinoParameter, idMotivoIncrementoParameter, montoTransferidoParameter);
        }
    
        public virtual int SP_EjecutaReproFed()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EjecutaReproFed");
        }
    }
}
