//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Representante
    {
        public int Pk_IdRepresentante { get; set; }
        public int Fk_IdUnidadEjecutora__UE { get; set; }
        public string Ap_Paterno { get; set; }
        public string Ap_Materno { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Colonia { get; set; }
        public int Fk_IdEstado__SIS { get; set; }
        public int Fk_IdMunicipio__SIS { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public System.Data.Entity.Spatial.DbGeography Ubicacion { get; set; }
        public int Fk_IdCargo { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Municipio Municipio { get; set; }
        public virtual UnidadEjecutora UnidadEjecutora { get; set; }
    }
}
