//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public Rol()
        {
            this.PrivilegiosXRols = new HashSet<PrivilegiosXRol>();
        }
    
        public int Pk_IdRol { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<PrivilegiosXRol> PrivilegiosXRols { get; set; }
    }
}
