//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACImportanciaEnfermedad
    {
        public int Pk_IdSACImportanciaEnfermedad { get; set; }
        public Nullable<int> Fk_IdCampania { get; set; }
        public string Cultivo { get; set; }
        public Nullable<int> Fk_IdMunicipio { get; set; }
        public Nullable<int> NumeroDeProductores { get; set; }
        public Nullable<double> SuperficieInund { get; set; }
        public Nullable<int> UnidadesProduccion { get; set; }
        public Nullable<double> NivelDeInfestacion { get; set; }
        public Nullable<double> SuperficieAfectada { get; set; }
        public Nullable<double> Mortalidad { get; set; }
        public Nullable<double> ValorDelaPerdida { get; set; }
    
        public virtual Municipio Municipio { get; set; }
        public virtual Campania Campania { get; set; }
    }
}
