//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_SENASICA_Storeds : DbContext
    {
        public DB_SENASICA_Storeds()
            : base("name=DB_SENASICA_Storeds")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int SP_CancelaReprogramacion_Campania(Nullable<int> fK_IdCampania__UE, ObjectParameter mensaje)
        {
            var fK_IdCampania__UEParameter = fK_IdCampania__UE.HasValue ?
                new ObjectParameter("FK_IdCampania__UE", fK_IdCampania__UE) :
                new ObjectParameter("FK_IdCampania__UE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CancelaReprogramacion_Campania", fK_IdCampania__UEParameter, mensaje);
        }
    
        public virtual int SP_Clona_TablasProcesoDeReprogramacion(Nullable<int> pK_IdCampania__UE, ObjectParameter mensaje)
        {
            var pK_IdCampania__UEParameter = pK_IdCampania__UE.HasValue ?
                new ObjectParameter("PK_IdCampania__UE", pK_IdCampania__UE) :
                new ObjectParameter("PK_IdCampania__UE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Clona_TablasProcesoDeReprogramacion", pK_IdCampania__UEParameter, mensaje);
        }
    
        public virtual int SP_CRUD_ProcesoReprogramacion(Nullable<int> pK_IdCampania__UE)
        {
            var pK_IdCampania__UEParameter = pK_IdCampania__UE.HasValue ?
                new ObjectParameter("PK_IdCampania__UE", pK_IdCampania__UE) :
                new ObjectParameter("PK_IdCampania__UE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CRUD_ProcesoReprogramacion", pK_IdCampania__UEParameter);
        }
    
        public virtual int Cierra_RepActividad(Nullable<int> idCampania, Nullable<int> idMes, Nullable<bool> cierra)
        {
            var idCampaniaParameter = idCampania.HasValue ?
                new ObjectParameter("IdCampania", idCampania) :
                new ObjectParameter("IdCampania", typeof(int));
    
            var idMesParameter = idMes.HasValue ?
                new ObjectParameter("IdMes", idMes) :
                new ObjectParameter("IdMes", typeof(int));
    
            var cierraParameter = cierra.HasValue ?
                new ObjectParameter("cierra", cierra) :
                new ObjectParameter("cierra", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cierra_RepActividad", idCampaniaParameter, idMesParameter, cierraParameter);
        }
    
        public virtual int Cierra_RepAdquisicion(Nullable<int> idCampania, Nullable<int> idMes, Nullable<bool> cierra)
        {
            var idCampaniaParameter = idCampania.HasValue ?
                new ObjectParameter("IdCampania", idCampania) :
                new ObjectParameter("IdCampania", typeof(int));
    
            var idMesParameter = idMes.HasValue ?
                new ObjectParameter("IdMes", idMes) :
                new ObjectParameter("IdMes", typeof(int));
    
            var cierraParameter = cierra.HasValue ?
                new ObjectParameter("cierra", cierra) :
                new ObjectParameter("cierra", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cierra_RepAdquisicion", idCampaniaParameter, idMesParameter, cierraParameter);
        }
    
        public virtual int SP_AperturaCampania(Nullable<int> idCierreMensual, string respuestaApertura, Nullable<System.DateTime> fechaCierreAutomatico, Nullable<bool> aperturaAceptada)
        {
            var idCierreMensualParameter = idCierreMensual.HasValue ?
                new ObjectParameter("IdCierreMensual", idCierreMensual) :
                new ObjectParameter("IdCierreMensual", typeof(int));
    
            var respuestaAperturaParameter = respuestaApertura != null ?
                new ObjectParameter("RespuestaApertura", respuestaApertura) :
                new ObjectParameter("RespuestaApertura", typeof(string));
    
            var fechaCierreAutomaticoParameter = fechaCierreAutomatico.HasValue ?
                new ObjectParameter("FechaCierreAutomatico", fechaCierreAutomatico) :
                new ObjectParameter("FechaCierreAutomatico", typeof(System.DateTime));
    
            var aperturaAceptadaParameter = aperturaAceptada.HasValue ?
                new ObjectParameter("AperturaAceptada", aperturaAceptada) :
                new ObjectParameter("AperturaAceptada", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AperturaCampania", idCierreMensualParameter, respuestaAperturaParameter, fechaCierreAutomaticoParameter, aperturaAceptadaParameter);
        }
    
        public virtual int SP_SolicitudAperturaCampania(Nullable<int> idCierreMensual, string motivosApertura)
        {
            var idCierreMensualParameter = idCierreMensual.HasValue ?
                new ObjectParameter("IdCierreMensual", idCierreMensual) :
                new ObjectParameter("IdCierreMensual", typeof(int));
    
            var motivosAperturaParameter = motivosApertura != null ?
                new ObjectParameter("MotivosApertura", motivosApertura) :
                new ObjectParameter("MotivosApertura", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SolicitudAperturaCampania", idCierreMensualParameter, motivosAperturaParameter);
        }
    }
}
