//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusAlcance
    {
        public StatusAlcance()
        {
            this.StatusAlcanceKardexes = new HashSet<StatusAlcanceKardex>();
            this.FlujoAlcances = new HashSet<FlujoAlcance>();
            this.FlujoAlcances1 = new HashSet<FlujoAlcance>();
            this.Accions = new HashSet<Accion>();
        }
    
        public int PK_IdStatusAlcance { get; set; }
        public string Nombre { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
    
        public virtual ICollection<StatusAlcanceKardex> StatusAlcanceKardexes { get; set; }
        public virtual ICollection<FlujoAlcance> FlujoAlcances { get; set; }
        public virtual ICollection<FlujoAlcance> FlujoAlcances1 { get; set; }
        public virtual ICollection<Accion> Accions { get; set; }
    }
}
