//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusCampania
    {
        public StatusCampania()
        {
            this.StatusCampaniaKardex_Repro = new HashSet<StatusCampaniaKardex_Repro>();
            this.FlujoCampanias = new HashSet<FlujoCampania>();
            this.FlujoCampanias1 = new HashSet<FlujoCampania>();
            this.StatusCampaniaKardexes = new HashSet<StatusCampaniaKardex>();
        }
    
        public int PK_IdStatusCampania { get; set; }
        public string Nombre { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
        public int Fk_IdAnio { get; set; }
    
        public virtual ICollection<StatusCampaniaKardex_Repro> StatusCampaniaKardex_Repro { get; set; }
        public virtual ICollection<FlujoCampania> FlujoCampanias { get; set; }
        public virtual ICollection<FlujoCampania> FlujoCampanias1 { get; set; }
        public virtual ICollection<StatusCampaniaKardex> StatusCampaniaKardexes { get; set; }
    }
}
