//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusCampaniaKardex
    {
        public int PK_IdStatusCampaniaKardex { get; set; }
        public int FK_IdStatusCampania__SIS { get; set; }
        public int FK_IdCampania__UE { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Comentarios { get; set; }
    
        public virtual Campania Campania { get; set; }
        public virtual StatusCampania StatusCampania { get; set; }
    }
}
