//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubComponente
    {
        public SubComponente()
        {
            this.UnidadResponsableXSubComponentes = new HashSet<UnidadResponsableXSubComponente>();
            this.UnidadResponsableXSubComponentePres = new HashSet<UnidadResponsableXSubComponentePre>();
            this.UnidadEjecutoras = new HashSet<UnidadEjecutora>();
            this.ProyectoAutorizadoes = new HashSet<ProyectoAutorizado>();
        }
    
        public int Pk_IdSubComponente { get; set; }
        public string Nombre { get; set; }
        public int Fk_IdIncentivo__SIS { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
    
        public virtual ICollection<UnidadResponsableXSubComponente> UnidadResponsableXSubComponentes { get; set; }
        public virtual ICollection<UnidadResponsableXSubComponentePre> UnidadResponsableXSubComponentePres { get; set; }
        public virtual ICollection<UnidadEjecutora> UnidadEjecutoras { get; set; }
        public virtual Incentivo Incentivo { get; set; }
        public virtual ICollection<ProyectoAutorizado> ProyectoAutorizadoes { get; set; }
    }
}
