//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoUnidad_UCAC
    {
        public TipoUnidad_UCAC()
        {
            this.UnidadesCertificarInoSACs = new HashSet<UnidadesCertificarInoSAC>();
            this.UnidadesCertificarInoSAC_Repro = new HashSet<UnidadesCertificarInoSAC_Repro>();
        }
    
        public int Pk_IdTipoUnidad_UCAC { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<UnidadesCertificarInoSAC> UnidadesCertificarInoSACs { get; set; }
        public virtual ICollection<UnidadesCertificarInoSAC_Repro> UnidadesCertificarInoSAC_Repro { get; set; }
    }
}
