//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoActividad
    {
        public TipoActividad()
        {
            this.ActividadXAccion_Repro = new HashSet<ActividadXAccion_Repro>();
            this.Actividads = new HashSet<Actividad>();
            this.ActividadXAccions = new HashSet<ActividadXAccion>();
        }
    
        public int Pk_IdTipoActividad { get; set; }
        public int Fk_IdTipoAccion { get; set; }
        public string Nombre { get; set; }
        public int FK_IdUnidadDeMedida { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
    
        public virtual UnidadDeMedida UnidadDeMedida { get; set; }
        public virtual TipoDeAccion TipoDeAccion { get; set; }
        public virtual ICollection<ActividadXAccion_Repro> ActividadXAccion_Repro { get; set; }
        public virtual ICollection<Actividad> Actividads { get; set; }
        public virtual ICollection<ActividadXAccion> ActividadXAccions { get; set; }
    }
}
