//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoProduccion
    {
        public TipoProduccion()
        {
            this.ImportanciaInoes = new HashSet<ImportanciaIno>();
            this.ImportanciaIno_Repro = new HashSet<ImportanciaIno_Repro>();
        }
    
        public int Pk_IdTipoProduccion { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<ImportanciaIno> ImportanciaInoes { get; set; }
        public virtual ICollection<ImportanciaIno_Repro> ImportanciaIno_Repro { get; set; }
    }
}
