//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDeBien
    {
        public TipoDeBien()
        {
            this.GirosXProvs = new HashSet<GirosXProv>();
            this.BienOServs = new HashSet<BienOServ>();
        }
    
        public int Pk_IdTipoDeBien { get; set; }
        public string Nombre { get; set; }
        public int Fk_IdPartida__SIS { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
        public int Fk_IdAnio { get; set; }
    
        public virtual ICollection<GirosXProv> GirosXProvs { get; set; }
        public virtual Partida Partida { get; set; }
        public virtual Anio Anio { get; set; }
        public virtual ICollection<BienOServ> BienOServs { get; set; }
    }
}
