//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDeRecurso
    {
        public TipoDeRecurso()
        {
            this.Accions = new HashSet<Accion>();
            this.Inventarios = new HashSet<Inventario>();
            this.ActividadXAccion_Repro = new HashSet<ActividadXAccion_Repro>();
            this.TESOFEs = new HashSet<TESOFE>();
            this.MinistracionesXComites = new HashSet<MinistracionesXComite>();
            this.ActividadXAccions = new HashSet<ActividadXAccion>();
        }
    
        public int Pk_IdTipoDeRecurso { get; set; }
        public string Nombre { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
    
        public virtual ICollection<Accion> Accions { get; set; }
        public virtual ICollection<Inventario> Inventarios { get; set; }
        public virtual ICollection<ActividadXAccion_Repro> ActividadXAccion_Repro { get; set; }
        public virtual ICollection<TESOFE> TESOFEs { get; set; }
        public virtual ICollection<MinistracionesXComite> MinistracionesXComites { get; set; }
        public virtual ICollection<ActividadXAccion> ActividadXAccions { get; set; }
    }
}
