//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoUnidad_Atendido
    {
        public TipoUnidad_Atendido()
        {
            this.AtendidoInoes = new HashSet<AtendidoIno>();
            this.AtendidoIno_Repro = new HashSet<AtendidoIno_Repro>();
        }
    
        public int Pk_IdTipoUnidad_Atendido { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<AtendidoIno> AtendidoInoes { get; set; }
        public virtual ICollection<AtendidoIno_Repro> AtendidoIno_Repro { get; set; }
    }
}
