//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadMedidaProduccion
    {
        public UnidadMedidaProduccion()
        {
            this.ImportanciaEconomicaSAs = new HashSet<ImportanciaEconomicaSA>();
            this.ImportanciaCultivoSACs = new HashSet<ImportanciaCultivoSAC>();
            this.ImportanciaEnfermedadSACs = new HashSet<ImportanciaEnfermedadSAC>();
            this.ImportanciaEnfermedadSAs = new HashSet<ImportanciaEnfermedadSA>();
            this.ImportanciaCultivoSAC_Repro = new HashSet<ImportanciaCultivoSAC_Repro>();
            this.ImportanciaEconomicaSA_Repro = new HashSet<ImportanciaEconomicaSA_Repro>();
            this.ImportanciaEnfermedadSA_Repro = new HashSet<ImportanciaEnfermedadSA_Repro>();
            this.ImportanciaEnfermedadSAC_Repro = new HashSet<ImportanciaEnfermedadSAC_Repro>();
        }
    
        public int Pk_IdUnidadMedidaProduccion { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<ImportanciaEconomicaSA> ImportanciaEconomicaSAs { get; set; }
        public virtual ICollection<ImportanciaCultivoSAC> ImportanciaCultivoSACs { get; set; }
        public virtual ICollection<ImportanciaEnfermedadSAC> ImportanciaEnfermedadSACs { get; set; }
        public virtual ICollection<ImportanciaEnfermedadSA> ImportanciaEnfermedadSAs { get; set; }
        public virtual ICollection<ImportanciaCultivoSAC_Repro> ImportanciaCultivoSAC_Repro { get; set; }
        public virtual ICollection<ImportanciaEconomicaSA_Repro> ImportanciaEconomicaSA_Repro { get; set; }
        public virtual ICollection<ImportanciaEnfermedadSA_Repro> ImportanciaEnfermedadSA_Repro { get; set; }
        public virtual ICollection<ImportanciaEnfermedadSAC_Repro> ImportanciaEnfermedadSAC_Repro { get; set; }
    }
}
