//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadesCertificarInoSA_Repro
    {
        public int Pk_IdUnidadesCertificarInoSA { get; set; }
        public Nullable<int> Fk_IdUnidadesCertificarInoSA_Orig { get; set; }
        public int Fk_IdCampania { get; set; }
        public int Fk_IdEspecie { get; set; }
        public int FK_IdFuncionZootecnica { get; set; }
        public int AntProgramado { get; set; }
        public int AntRealizado { get; set; }
        public double AntPorcentajeCumplimiento { get; set; }
        public int ActProgramado { get; set; }
        public int ActRealizado { get; set; }
        public double ActPorcentajeCumplimiento { get; set; }
    
        public virtual Campania_Repro Campania_Repro { get; set; }
        public virtual Especie Especie { get; set; }
        public virtual FuncionZootecnica FuncionZootecnica { get; set; }
    }
}
