//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadDeMedida
    {
        public UnidadDeMedida()
        {
            this.TipoActividads = new HashSet<TipoActividad>();
            this.Accions = new HashSet<Accion>();
            this.NecesidadXAccions = new HashSet<NecesidadXAccion>();
            this.TipoDeAccions = new HashSet<TipoDeAccion>();
            this.ProgramaAnualAdq_Repro = new HashSet<ProgramaAnualAdq_Repro>();
            this.ActividadXAccion_Repro = new HashSet<ActividadXAccion_Repro>();
            this.ProgramaAnualAdqs = new HashSet<ProgramaAnualAdq>();
            this.Actividads = new HashSet<Actividad>();
            this.ActividadXAccions = new HashSet<ActividadXAccion>();
            this.BienOservByUnidadMedidas = new HashSet<BienOservByUnidadMedida>();
        }
    
        public int Pk_IdUnidadDeMedida { get; set; }
        public string Nombre { get; set; }
        public int Fk_IdAnio { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
    
        public virtual ICollection<TipoActividad> TipoActividads { get; set; }
        public virtual ICollection<Accion> Accions { get; set; }
        public virtual ICollection<NecesidadXAccion> NecesidadXAccions { get; set; }
        public virtual ICollection<TipoDeAccion> TipoDeAccions { get; set; }
        public virtual Anio Anio { get; set; }
        public virtual ICollection<ProgramaAnualAdq_Repro> ProgramaAnualAdq_Repro { get; set; }
        public virtual ICollection<ActividadXAccion_Repro> ActividadXAccion_Repro { get; set; }
        public virtual ICollection<ProgramaAnualAdq> ProgramaAnualAdqs { get; set; }
        public virtual ICollection<Actividad> Actividads { get; set; }
        public virtual ICollection<ActividadXAccion> ActividadXAccions { get; set; }
        public virtual ICollection<BienOservByUnidadMedida> BienOservByUnidadMedidas { get; set; }
    }
}
