//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadResponsableXSubComponentePre
    {
        public int Pk_IdUnidadResponsableXSubComponentePres { get; set; }
        public int FK_IdAnio { get; set; }
        public int Fk_IdSubComponente { get; set; }
        public int Fk_IdUnidadResponsable { get; set; }
    
        public virtual Anio Anio { get; set; }
        public virtual SubComponente SubComponente { get; set; }
        public virtual UnidadResponsable UnidadResponsable { get; set; }
    }
}
