//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vigencia
    {
        public int Pk_IdVigencia { get; set; }
        public int Fk_IdUnidadEjecutora { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string NumeroRegistro { get; set; }
        public string Documento { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
    
        public virtual UnidadEjecutora UnidadEjecutora { get; set; }
    }
}
