//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CampaniasMontosTransversales
    {
        public int Fk_IdPrograma__SIS { get; set; }
        public int Fk_IdComponente { get; set; }
        public int Fk_IdIncentivo__SIS { get; set; }
        public int Fk_IdSubComponente__SIS { get; set; }
        public int Fk_IdRegion { get; set; }
        public int Fk_IdEstado { get; set; }
        public int Fk_IdAnio { get; set; }
        public Nullable<int> Fk_IdUnidadResponsable { get; set; }
        public Nullable<int> Fk_IdUnidadEjecutora { get; set; }
        public Nullable<int> Fk_IdTipoCampania { get; set; }
        public int Fk_IdProyectoAutorizado { get; set; }
        public string IE { get; set; }
        public string SubComponente { get; set; }
        public string ProyectoAutorizado { get; set; }
        public string CoordinadorCampania { get; set; }
        public int Pk_IdCampania { get; set; }
        public string NombreCampania { get; set; }
        public string Introduccion { get; set; }
        public string SituacionActual { get; set; }
        public string ObjetivoEstrategico { get; set; }
        public string MetaAnual { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string NombreArchivoAnexo { get; set; }
        public string NombreArchivoInforme { get; set; }
        public string CT_User { get; set; }
        public System.DateTime CT_Date { get; set; }
        public Nullable<int> Fk_IdCoordinador { get; set; }
        public Nullable<int> Fk_IdProyectoPresupuesto { get; set; }
        public decimal RecFed { get; set; }
        public decimal RecEst { get; set; }
        public decimal RecPro { get; set; }
        public decimal RecTot { get; set; }
        public string StatusKardex { get; set; }
        public Nullable<bool> esEditable { get; set; }
        public Nullable<System.DateTime> FechaModificacionStatus { get; set; }
        public decimal RecSol_Fed { get; set; }
        public decimal RecSol_Est { get; set; }
        public decimal RecSol_Pro { get; set; }
        public string NombreInf_PrimerTrim { get; set; }
        public string NombreInf_SegundoTrim { get; set; }
        public string NombreInf_TercerTrim { get; set; }
        public string NombreInf_CuartoTrim { get; set; }
        public Nullable<decimal> presSinRegistrar_Fed { get; set; }
        public Nullable<decimal> presSinRegistrar_Est { get; set; }
        public Nullable<decimal> presSinRegistrar_Pro { get; set; }
        public string StatusActual { get; set; }
        public decimal MontoTransversales_Fed { get; set; }
        public decimal MontoTransversales_Est { get; set; }
        public decimal MontoTransversales_Pro { get; set; }
    }
}
