//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_HistoricoReproPT
    {
        public Nullable<int> Fk_IdCampania_Orig { get; set; }
        public int Consecutivo_Repro { get; set; }
        public System.DateTime CT_FechaRepro { get; set; }
        public Nullable<int> Anio { get; set; }
    }
}
