//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PresupuestoCampania
    {
        public int Pk_IdCampania { get; set; }
        public string StatusKardex { get; set; }
        public int Fk_IdAnio { get; set; }
        public int Fk_IdEstado__SIS { get; set; }
        public string Estado { get; set; }
        public string UnidadResponsable { get; set; }
        public string UnidadEjecutora { get; set; }
        public string Proyecto { get; set; }
        public decimal RecFed { get; set; }
        public decimal RecSol_Fed { get; set; }
        public Nullable<decimal> Rec_Gastado { get; set; }
        public Nullable<decimal> SaldoDisponible { get; set; }
    }
}
