//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ReporteAdquisiciones
    {
        public int Pk_IdProgramaAnualAdq { get; set; }
        public Nullable<int> Fk_IdCampania__UE { get; set; }
        public int Fk_IdAnio__SIS { get; set; }
        public Nullable<int> Fk_IdUnidadEjecutora__UE { get; set; }
        public int Fk_IdUnidadResponsable__UE { get; set; }
        public int Fk_IdEstado__SIS { get; set; }
        public Nullable<int> Fk_IdRegion { get; set; }
        public Nullable<int> Fk_IdCoordinador { get; set; }
        public string IE { get; set; }
        public string Campania { get; set; }
        public string AccionXCampania { get; set; }
        public string BienOServ { get; set; }
        public string UnidadMedida { get; set; }
        public Nullable<decimal> Cant_Anual { get; set; }
        public Nullable<decimal> imp_Anual { get; set; }
        public decimal Gastos { get; set; }
        public string EstadoDeGasto { get; set; }
        public string TipoRecurso { get; set; }
    }
}
