//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_TipoActividad
    {
        public int IdTipoActividad { get; set; }
        public string ConceptoApoyo { get; set; }
        public string ProyectoAutorizado { get; set; }
        public string TipoAccion { get; set; }
        public string TipoActividad { get; set; }
        public string UnidadMedida { get; set; }
        public int IdAnio { get; set; }
        public int Anio { get; set; }
    }
}
