//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Users
    {
        public string ID { get; set; }
        public string Rol { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Pk_IdEstado { get; set; }
        public string Estado { get; set; }
        public string UnidadEjecutora { get; set; }
        public Nullable<int> Pk_IdUnidadEjecutora { get; set; }
        public string UnidadResponsable { get; set; }
        public Nullable<int> Pk_IdUnidadResponsable { get; set; }
    }
}
