//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXMVCWebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WebServicesModel : DbContext
    {
        public WebServicesModel()
            : base("name=WebServicesModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VW_TipoActividad> VW_TipoActividad { get; set; }
    
        [DbFunction("WebServicesModel", "GetEstados")]
        public virtual IQueryable<GetEstados_Result1> GetEstados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetEstados_Result1>("[WebServicesModel].[GetEstados]()");
        }
    
        [DbFunction("WebServicesModel", "GetPEFXEstados")]
        public virtual IQueryable<GetPEFXEstados_Result1> GetPEFXEstados(Nullable<int> anio)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetPEFXEstados_Result1>("[WebServicesModel].[GetPEFXEstados](@Anio)", anioParameter);
        }
    
        [DbFunction("WebServicesModel", "GetPresComite_All")]
        public virtual IQueryable<GetPresComite_All_Result1> GetPresComite_All(Nullable<int> anio)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetPresComite_All_Result1>("[WebServicesModel].[GetPresComite_All](@Anio)", anioParameter);
        }
    
        [DbFunction("WebServicesModel", "GetPresComite_ByComite")]
        public virtual IQueryable<GetPresComite_ByComite_Result1> GetPresComite_ByComite(Nullable<int> anio, Nullable<int> idComite)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(int));
    
            var idComiteParameter = idComite.HasValue ?
                new ObjectParameter("IdComite", idComite) :
                new ObjectParameter("IdComite", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetPresComite_ByComite_Result1>("[WebServicesModel].[GetPresComite_ByComite](@Anio, @IdComite)", anioParameter, idComiteParameter);
        }
    
        [DbFunction("WebServicesModel", "GetProveedores_All")]
        public virtual IQueryable<GetProveedores_All_Result1> GetProveedores_All()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetProveedores_All_Result1>("[WebServicesModel].[GetProveedores_All]()");
        }
    
        [DbFunction("WebServicesModel", "GetProveedores_ByEstado")]
        public virtual IQueryable<GetProveedores_ByEstado_Result1> GetProveedores_ByEstado(Nullable<int> idEstado)
        {
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetProveedores_ByEstado_Result1>("[WebServicesModel].[GetProveedores_ByEstado](@IdEstado)", idEstadoParameter);
        }
    
        [DbFunction("WebServicesModel", "GetUnidadesResponsables")]
        public virtual IQueryable<GetUnidadesResponsables_Result2> GetUnidadesResponsables()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetUnidadesResponsables_Result2>("[WebServicesModel].[GetUnidadesResponsables]()");
        }
    
        [DbFunction("WebServicesModel", "GetComites_All")]
        public virtual IQueryable<GetComites_All_Result1> GetComites_All()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetComites_All_Result1>("[WebServicesModel].[GetComites_All]()");
        }
    
        [DbFunction("WebServicesModel", "GetComites_ByComite")]
        public virtual IQueryable<GetComites_ByComite_Result1> GetComites_ByComite(Nullable<int> idComite)
        {
            var idComiteParameter = idComite.HasValue ?
                new ObjectParameter("IdComite", idComite) :
                new ObjectParameter("IdComite", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetComites_ByComite_Result1>("[WebServicesModel].[GetComites_ByComite](@IdComite)", idComiteParameter);
        }
    
        [DbFunction("WebServicesModel", "GetComites_ByEstado")]
        public virtual IQueryable<GetComites_ByEstado_Result1> GetComites_ByEstado(Nullable<int> idEstado)
        {
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetComites_ByEstado_Result1>("[WebServicesModel].[GetComites_ByEstado](@IdEstado)", idEstadoParameter);
        }
    
        [DbFunction("WebServicesModel", "GetComites_ByUR")]
        public virtual IQueryable<GetComites_ByUR_Result1> GetComites_ByUR(Nullable<int> idUR)
        {
            var idURParameter = idUR.HasValue ?
                new ObjectParameter("IdUR", idUR) :
                new ObjectParameter("IdUR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetComites_ByUR_Result1>("[WebServicesModel].[GetComites_ByUR](@IdUR)", idURParameter);
        }
    
        [DbFunction("WebServicesModel", "GetProyectosAutorizadosComitesById")]
        public virtual IQueryable<GetProyectosAutorizadosComitesById_Result> GetProyectosAutorizadosComitesById(Nullable<int> anio, Nullable<int> idComite)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(int));
    
            var idComiteParameter = idComite.HasValue ?
                new ObjectParameter("IdComite", idComite) :
                new ObjectParameter("IdComite", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetProyectosAutorizadosComitesById_Result>("[WebServicesModel].[GetProyectosAutorizadosComitesById](@Anio, @IdComite)", anioParameter, idComiteParameter);
        }
    }
}
